### ISSUE TITLE
🌳🌳开源课程学习班

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#131]
2022 年的开源课程学习班从8月1日正式开始，为期四周：

- [x] #136
- [x] #132
- [x] #133
- [ ] 第四周：Open Source for Business 共读（组织者 @will-ww ）

组织者角色的工作包括：确定分享人员、分享内容、分享形式、反馈等，可以一起在本 issue 下面开展讨论~

**Comment by will-ww** [comment]
2022 年的开源课程学习班从8月1日正式开始，为期四周：

- [ ] 第一周：邀请外部专业人士一起来分享我们的两本新书《[拥抱开源](https://www.amazon.com/How-Open-Source-Ate-Software-ebook/dp/B08WBYGW5T/ref=sr_1_2?crid=12XX6BUZMN6J&keywords=How+Open+Source+Ate+Software&qid=1658447255&s=audible&sprefix=how+open+source+ate+software%2Caudible%2C306&sr=1-2)》、《[开放式协作](https://www.amazon.com/Working-Public-Making-Maintenance-Software/dp/B08KWR85F8/ref=sr_1_1?crid=2J9F4K0TUFVLP&keywords=working+in+public&qid=1658447140&sprefix=working+in+publi%2Caps%2C615&sr=8-1)》（组织者 @xiaoya-yaya ）
- [ ] 第二周：FOSS 课程的学习 （组织者 @bifenglin  ）
- [ ] 第三周：COSS 课程的学习（组织者 @will-ww ）
- [ ] 第四周：Open Source for Business 共读（组织者 @frank-zsy ）

组织者角色的工作包括：确定分享人员、分享内容、分享形式、反馈等，可以一起在本 issue 下面开展讨论~

**Comment by will-ww** [comment]
我的几个建议是：
- 第一周，@xiaoya-yaya 可以邀请我们两本书籍的翻译或校对者，进行分享，这个比较轻松，可以多互动与讨论；
- 第二周、第三周，结合去年两门课程字幕的翻译，以一年级的同学为主进行分享学习；
- 第四周，新书即将出版，我去看看能否请到人来一起分享，或者我们内部也来消化下。

**Comment by will-ww** [comment]
时间上初步设想为，整个 8 月份，周一、周二、周四、周五，每天晚上 8: 30 ~ 10: 00

**Comment by will-ww** [comment]
> 是不是可以开一个时间表，我希望和具体的日期对上号比较好。比如某月某日是谁什么主题。

即将出炉~

**Comment by will-ww** [comment]
第一周是不是可以考虑办成读书分享会，几个人一起围绕书中的几个主题来聊聊天，轻松快乐~ @xiaoya-yaya

**Comment by xiaoya-yaya** [comment]
听起来不错，我来思考一下

**Comment by will-ww** [comment]
![image](https://user-images.githubusercontent.com/15010826/180597604-0138f8f8-4fb0-4800-9558-db2f8d9a07d3.png)

两位老师都给 WIP 写了推荐语的，也都对开源教育感兴趣，值得请来聊一次~  :-)

**Comment by will-ww** [comment]
本次开放原子峰会，最大的收获就是，我们第四周的活动，将邀请《商业开源》这本书的译者（刘伟老师），以及振华老师这样的法务专家一起来分享与讨论，启发非常大~

![image](https://user-images.githubusercontent.com/15010826/181863854-2f8e5d56-8e10-42fe-8999-b63598579ad9.png)

![image](https://user-images.githubusercontent.com/15010826/181863901-112999e9-b1ce-4090-a51b-9bf10bff6b9e.png)

**Comment by wangleo61** [comment]
[Work In Public-Chapter 3.pdf](https://github.com/X-lab2017/open-wonderland/files/9244105/Work.In.Public-Chapter.3.pdf)
