### ISSUE TITLE
🌳🌳🌳第二周：FOSS 课程的学习 （组织者 @birdflyi）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#132]
根据《[开源软件通识基础](https://xlab2017.yuque.com/docs/share/5ef3b587-071d-4ca8-96ba-e66f262edc77?#%20%E3%80%8ADaSE%20%E7%A0%94%E7%A9%B6%E7%94%9F%E6%96%B0%E7%94%9F%E7%AC%AC%E4%B8%80%E8%AF%BE%E3%80%8B)》，以及[去年字幕翻译情况](https://shimo.im/docs/wYDPjqdWvyCVqtJX)的安排，建议今年讲解如下重要模块：

- B01：Overview and History（50min）@xiaoya-yaya
- B02：Intellectual Property（60min）@fruitLoving-yf
- B03：Corporate Governance（60min）@@gymgym1212
- B04：Project Communities（60min）@tieway59
- B05：Engineering Processes（60min）@tieway59
- B06：Development Tooling（12min）@sjb
- C01：Software Industry（70min）@longyanz
- C02：Developer Foundation（70min）@xgdyp
- C03：User Foundation（60min）@xgdyp
- C04：Labor economics（60min）@longyanz

下面内容待定：
- Commercial Open Source and the Cloud（14min）
- Single-Vendor Firms（35min）
- Open Source and Public Policy（26min）
- Open sourcing research software（15min）

Youtube 链接：https://www.youtube.com/playlist?list=PLQ2ODVSeOYlXtMfsO-JrL--lnFRbAaLHL
旧课件链接(需登录到 JihuLab)：https://jihulab.com/opensourcecoursetranslation/foss
旧字幕：https://shimo.im/docs/WlArzzWRJvUwEnA2

**Comment by will-ww** [comment]
几个想法：
- 分成 A、B、C、D 等四个主要模块
- 每个模块高年级的同学，带上一个低年级的同学共同来讲解，以低年级的为主 
- 同时，低年级的同学负责校对字幕，9月份连同 Dirk 的视频一起上线
- 同学们分享的视频同样录制，是否上线根据分享的质量来确定

**Comment by TieWay59** [comment]
好的，请问我可以认领 B 模块么？

**Comment by longyanz** [comment]
报名C03，C04

**Comment by xgdyp** [comment]
报名C02，C03

**Comment by longyanz** [comment]
报名C01，C04

**Comment by xiaoya-yaya** [comment]
B01

**Comment by xgdyp** [comment]
@will-ww  请问下王老师，怎么联系之前的学长学姐呢，是根据以前字幕的分工还是去年讲课的分工呢？

**Comment by JingbenShi668** [comment]
> @will-ww 请问下王老师，怎么联系之前的学长学姐呢，是根据以前字幕的分工还是去年讲课的分工呢？
我以为去年讲过的学姐学长是不用再讲的😂

**Comment by will-ww** [comment]
> @will-ww 请问下王老师，怎么联系之前的学长学姐呢，是根据以前字幕的分工还是去年讲课的分工呢？

去年的内容实际上就是你们的素材了，由今年讲课的同学全权负责，具体我们可以在这个 issue 下面来讨论。

- https://github.com/X-lab2017/open-wonderland/issues/135

**Comment by will-ww** [comment]
> > @will-ww 请问下王老师，怎么联系之前的学长学姐呢，是根据以前字幕的分工还是去年讲课的分工呢？

你就是之前的学长呀~

**Comment by xgdyp** [comment]
> > @will-ww 请问下王老师，怎么联系之前的学长学姐呢，是根据以前字幕的分工还是去年讲课的分工呢？
> 
> 去年的内容实际上就是你们的素材了，由今年讲课的同学全权负责，具体我们可以在这个 issue 下面来讨论。
> 
> * [关于 FOSS 和 COSS #135](https://github.com/X-lab2017/open-wonderland/issues/135)

明白了～

**Comment by bifenglin** [comment]
根据https://github.com/X-lab2017/open-wonderland/issues/135#issuecomment-1194949195 需要大家补充课件字幕等内容放进https://github.com/X-lab2017/oss101-awesome-list仓库中。
其中日程安排如下：
https://github.com/X-lab2017/oss101-awesome-list/blob/main/agenda.md

@xiaoya-yaya @fruitLoving-yf @@gymgym1212 @TieWay59 @JingbenShi668 @longyanz @xgdyp @@longyanz

**Comment by will-ww** [comment]
> 根据[#135 (comment)](https://github.com/X-lab2017/open-wonderland/issues/135#issuecomment-1194949195) 需要大家补充课件字幕等内容放进[https://github.com/X-lab2017/oss101-awesome-list仓库中。](https://github.com/X-lab2017/oss101-awesome-list%E4%BB%93%E5%BA%93%E4%B8%AD%E3%80%82) 其中日程安排如下： https://github.com/X-lab2017/oss101-awesome-list/blob/main/agenda.md
> 
> @xiaoya-yaya @fruitLoving-yf @@gymgym1212 @TieWay59 @JingbenShi668 @longyanz @xgdyp @@longyanz

你需要说清楚怎样的放置方法，即放在哪个文件夹下，以什么样的命名方式等~ @bifenglin

**Comment by TieWay59** [comment]
> 旧课件链接(需登录到 JihuLab)：https://jihulab.com/opensourcecoursetranslation/foss

我打不开这个连接，404。

**Comment by will-ww** [comment]
> 404

可以找 @JingbenShi668 开通下 GitLab 的账号~

**Comment by kongzhongsanbu** [comment]
交换一下：COSS B01由 @longyanz  来讲；  FOSS C01由 @kongzhongsanbu 来讲

**Comment by bifenglin** [comment]
> 

已修改

**Comment by TieWay59** [comment]
好，我的 GitLab 账号是 51215903062@stu.ecnu.edu.cn 烦请有空时为我开通。

**Comment by gymgym1212** [comment]
@TieWay59 Done.

**Comment by wangleo61** [comment]
期待

**Comment by will-ww** [comment]
感谢各位，圆满完成~
