### ISSUE TITLE
🌳🌳🌳第三周：COSS 课程的学习（组织者  @bifenglin）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#133]
根据《[开源软件通识基础](https://xlab2017.yuque.com/docs/share/5ef3b587-071d-4ca8-96ba-e66f262edc77?#%20%E3%80%8ADaSE%20%E7%A0%94%E7%A9%B6%E7%94%9F%E6%96%B0%E7%94%9F%E7%AC%AC%E4%B8%80%E8%AF%BE%E3%80%8B)》，以及[去年字幕翻译情况](https://shimo.im/docs/wYDPjqdWvyCVqtJX)的安排，建议今年讲解如下重要模块：

- B01：The software industry（60min）@kongzhongsanbu
- B02：Software products（60min）@bifenglin
- B03：Software vendors（60min）@yoyo-wu98
- B04：Business models （60min）@yoyo-wu98
- C01：Open source software（60min）@tyn1998
- C02：Open source projects（60min）@tyn1998
- C03：Commercial open source（60min）@zhicheng-ning
- C04：Cloud service strategies（40min）@zhicheng-ning

下面的内容待定：
- D01：Software startups（50min）
- D02：Research and startup（50min）@birdflyi
- D03：University spin-offs（40min）
- D04：Startup fundraising（40min）

Youtube 链接：https://www.youtube.com/playlist?list=PLQ2ODVSeOYlX_ssU08e-9x_ggESeBsyhh
Slides：https://github.com/dirkriehle/coss-course/tree/main/Generated/Lecture%20slides
旧课件链接（需要登录到 JihuLab）：https://jihulab.com/opensourcecoursetranslation/coss
旧字幕：https://shimo.im/docs/WlArzzWRJvUwEnA2

**Comment by tyn1998** [comment]
报名C01, C02。

**Comment by zhicheng-ning** [comment]
C03、C04

**Comment by yoyo-wu98** [comment]
B03、B04

**Comment by kongzhongsanbu** [comment]
B01

**Comment by birdflyi** [comment]
D02：Research and startup（50min）

**Comment by bifenglin** [comment]
根据https://github.com/X-lab2017/open-wonderland/issues/135#issuecomment-1194949195 需要大家补充课件字幕等内容放进https://github.com/X-lab2017/oss101-awesome-list仓库中。
其中日程安排如下：
https://github.com/X-lab2017/oss101-awesome-list/blob/main/agenda.md

@kongzhongsanbu @yoyo-wu98 @tyn1998  @zhicheng-ning

**Comment by will-ww** [comment]
感谢各位，圆满完成~
