### ISSUE TITLE
🌳🌳🌳第一周：《开放式协作》 和 《拥抱开源》 读书会（组织者 @xiaoya-yaya）

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-wonderland#136]
## 时间计划表
⏰ 每晚 20:30 - 22:00
📌 #腾讯会议：553-7140-7618
https://meeting.tencent.com/dm/aX9Ixd71UOW4

|日期 | 书籍| 重点章节 | 主题 | 主要分享人 |
|-- |-- |--| --| -- |
|8.1 周一 |拥抱开源 | C03| 什么是法律？| 孙振华 @sunzhh02|
|8.2 周二 | 开放式协作 |第三章 | 角色，激励和关系 | 王永雷@wangleo61|
|8.4 周四 | 开放式协作 |第五章 |  管理生产的成本 | 庄表伟@zhuangbiaowei|
|8.5 周五 |拥抱开源 | C06 | 商业模式与加速发展 | 边思康@richardbsk|

**Comment by will-ww** [comment]
目前初步安排是：

- 周一、周二（入门）：《拥抱开源》
-- 候选人（包括但不限）：张琰彬、耿航、边Sir、老庄、永磊、姜宁、李思颖、振华、实验室同学
- 周四、周五（进阶）：《开放式协作》
-- 候选人（包括但不限）：老庄、姜宁、永雷、Frank、Emily、实验室同学

**Comment by wangleo61** [comment]
报名聊第二章的：角色，激励和关系
tips:
1.开头引用Star Simpson的言论引发的讨论，网络社区存在的原因和意义
2.开源社区的低贴现率激发人们的长期的思维
3.加入开源社区的意义（金钱，个人满足感）
4.开源社区的运维，以及由此带来的风险
5.活跃贡献者更加专业么（安全知识或管理社区领域）
6.待续

**Comment by zhuangbiaowei** [comment]
报名聊第五章

**Comment by wangleo61** [comment]
[Uploading Work In Public-Chapter 3.pdf…]()

**Comment by wangleo61** [comment]
[Work In Public-Chapter 3.pdf](https://github.com/X-lab2017/open-wonderland/files/9244099/Work.In.Public-Chapter.3.pdf)

**Comment by will-ww** [comment]
> [Work In Public-Chapter 3.pdf](https://github.com/X-lab2017/open-wonderland/files/9244099/Work.In.Public-Chapter.3.pdf)

谢谢永雷老师的分享~

**Comment by will-ww** [comment]
感谢各位，圆满完成~
