### ISSUE TITLE
需要对开源课程的日程安排做信息补充与重构

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#151]
目前的[开源课程日程安排](https://github.com/X-lab2017/open-wonderland/blob/main/%F0%9F%8C%B32022-XSOSI-OpenCourse.md)，需要补充以下几个信息：

- [ ] 适当的做些美化与信息完善，例如[参见这里](https://github.com/X-lab2017/open-research/tree/main/agenda)
- [ ] 需要补充主持人一栏，并填上对应的主持人
- [ ] #154
- [ ] 如果一次有两位同学的话，需要明确哪位同学讲两个部分，并分别列出上面的信息
- [ ] 可以考虑再加一列“讨论”，在 Discussion 中开对应的讨论贴，然后链接进去

最后的日程安排，看上去大致是这个样子：

![image](https://user-images.githubusercontent.com/15010826/182757757-aa8af1f4-3822-456f-8713-53ee1d2aec26.png)

看看是否合理？还需要什么优化~

**Comment by will-ww** [comment]
考虑到 md 的形式，我对列做了些合并，表太宽的话会影响美观~

**Comment by bifenglin** [comment]
那么COSS第五节放到第三周周日（21号）晚上8.30-10点了。

> 考虑到 md 的形式，我对列做了些合并，表太宽的话会影响美观~
> 
> 另外，周日的晚上的时间也是可以拿出来的，这样可以将 FOSS 和 COSS 放到一周里面讲完~

**Comment by will-ww** [comment]
感谢各位，圆满完成~
