### ISSUE TITLE
讲师与主持人的注意事项与检查清单

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#152]
讲师注意事项与检查清单：

注意事项：
- 课程内容与结构，我们就按照 Dirk 教授的两门课程来，讲里面最重要的部分
- 每节课控制在 30 ~ 45 分钟左右（相较于 Dirk 教授的每次课在 60 分钟左右）
- PPT 统一用 Dirk 教授的，也可以在去年课件的基础上迭代，需要做些中文化的工作，重要的专业术语同时保留英文，尽量对听众友好
- 根据需要可以对 Dirk 教授的课件进行删减与增加，以保证更好的授课效果

每次课程的检查清单：
- 是否完整学习了 Dirk 教授对应的课程
- 是否至少看过一遍去年同学分享的视频
- 是否阅读过至少一遍去年翻译的对应的课程字幕
- 课程分享前，是否已经将原课程的课件、视频、字幕，更新到日程对应的位置（主持人统一放置）
- 课程分享前，是否已经将课件链接到日程对应的位置（讲师放置，主持人检查并提醒）
- 课程分享前，是否已经将课程的讨论帖建好，并放置到日程对应的位置（主持人统一放置）
- 课程分享前，主持人提醒讲师按时讲授，并在群里鼓励大家按时参加
- 课程分享中，主任人录制屏幕，并维护好秩序，两次课之间可以考虑休息几分钟（主持人灵活把握）
- 课程分享后，主持人是否将对应视频进行上传B站，并将链接放置到日程对应的位置
- 课程分享前后，鼓励大家在 Discussion 中进行讨论

可以继续完善~

**Comment by bifenglin** [comment]
这里的原课件是指dirk教授的课件么

**Comment by will-ww** [comment]
> 这里的原课件是指dirk教授的课件么

是的

**Comment by xgdyp** [comment]
收到

**Comment by will-ww** [comment]
感谢各位，圆满完成~
