### ISSUE TITLE
关于 OpenDigger 和 Hypercrx 双周例会的启动

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#180]
根据本学期的[总体安排](https://github.com/X-lab2017/open-wonderland/blob/main/%F0%9F%8D%812022-2023-Autumn-Term-Activities-Schedule.md)，请 OpenDigger 和 Hypercrx 本周相应启动双周例会机制，阶段性实时同步项目信息。

- [x] OpenDigger @xgdyp 
- [x] Hypercrx @tyn1998 

几点建议包括：

- 在各自的项目仓库上运作双周会议
- 时间上大家确定好，以往是中午
- Hypercrx 的开发相对，是一个开发者为主，研发进度不断向前的会议
- OpenDigger 是一个数据基础型项目，既有自己的开发进度，又需要较多的外部协调，包括支撑年报、Hypercrx、OpenLearderboard、大屏等不同的项目，这个需要再好好设计下，仅以翔宇拉动更多的人一起参与与讨论（小雅、老毕、娄博等），尽量通过 issue 等形式来运作。

两边的会议框架定好后，可以类似：研讨会•开源研究（科研）： [🍁[查看](https://github.com/X-lab2017/open-research/blob/main/agenda/%F0%9F%8D%812022-2023-Autumn-Term-OS-Seminar.md)]

将内容，增加到”🍁2022-2023-Autumn-Term-Activities-Schedule.md“ 文件中，本 issue 随即就可以 close 掉了。

**Comment by tyn1998** [comment]
@will-ww 王老师好，关于“在Hypercrx仓库中运作双周会议”，我是这么想的：

由于Hypercrx是一个代码仓库，我认为在项目目录中增加有关于会议计划的markdown文件不大合适。因为这样不仅在项目中多出了与项目代码本身没有直接联系的文件，还需要经常提PR来更新markdown文件的内容。

但是，Discussion是个好地方，我可以开一个discussion作为汇总discussion并pin在最上方，然后每两周开一个discussion作为当周的会议discussion，并且链接到汇总discussion中。

总的来说，Hypercrx的双周会议依靠Discussion运转，可能不会涉及到Issues。王老师觉得这样可以吗？

**Comment by will-ww** [comment]
> @will-ww 王老师好，关于“在Hypercrx仓库中运作双周会议”，我是这么想的：
> 
> 由于Hypercrx是一个代码仓库，我认为在项目目录中增加有关于会议计划的markdown文件不大合适。因为这样不仅在项目中多出了与项目代码本身没有直接联系的文件，还需要经常提PR来更新markdown文件的内容。
> 
> 但是，Discussion是个好地方，我可以开一个discussion作为汇总discussion并pin在最上方，然后每两周开一个discussion作为当周的会议discussion，并且链接到汇总discussion中。
> 
> 总的来说，Hypercrx的双周会议依靠Discussion运转，可能不会涉及到Issues。王老师觉得这样可以吗？

同意，仓库肯定是代码为主，这种例行事宜用 issue 和 Discussion 更合适。至于哪个，你们可以定，issue 我觉得也是个挺好的地方，优势和区别，我还没想清楚。:-)

**Comment by tyn1998** [comment]
那我就先试试纯Discussion的方式了~

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/32434520/189811990-bff3ced9-8919-43ab-beb2-d98b192e405d.png">

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/32434520/189812203-7112a76c-6007-4074-9afc-009781c57cb0.png">

**Comment by will-ww** [comment]
没问题，咱们迭代优化~

**Comment by xgdyp** [comment]
@tyn1998  能帮opendigger搞一个不

**Comment by xgdyp** [comment]
关于opendigger组会，我目前打算讨论的内容是开源年报问卷篇的相关设计～

**Comment by tyn1998** [comment]
> @tyn1998 能帮opendigger搞一个不

如果也采用Discussion的方式，那很简单的，但是我没权限哈。OpenDigger可能也要求全英文的，这个需要注意，这方面可能会花点时间。
