### ISSUE TITLE
关于 OpenPerf 与开源数据周会的安排

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#181]
根据本学期的[总体安排](https://github.com/X-lab2017/open-wonderland/blob/main/%F0%9F%8D%812022-2023-Autumn-Term-Activities-Schedule.md)，请 OpenPerf 与开源数据，本周相应启动周例会机制，阶段性实时同步项目信息。

- [x] 研讨会•开源数据 @bifenglin 

我想开源数据方向的研讨会，将延续我们 AllSpark 的风格，主要以更加具体的开源项目，例如 OpenPerf 等为主，为大家在各种开源业务活动中的，数据工程方面的问题，提供各种支持。

会议框架定好后，可以类似：研讨会•开源研究（科研）： [🍁[查看](https://github.com/X-lab2017/open-research/blob/main/agenda/%F0%9F%8D%812022-2023-Autumn-Term-OS-Seminar.md)]

将内容，增加到”🍁2022-2023-Autumn-Term-Activities-Schedule.md“ 文件中，本 issue 随即就可以 close 掉了。 

个人觉得，首先博士生们，应该都 involve 进来~

**Comment by bifenglin** [comment]
目前以openperf会议为载体（前身allspark），包括但不仅限于开源数据相关内容，具体安排详见pr:https://github.com/X-lab2017/open-wonderland/pull/184/commits/812cf3cf41a73adae6067a2eff0bbdb027178b9d
