### ISSUE TITLE
木兰开源社区治理大屏（@zhicheng-ning ）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#211]

**Comment by will-ww** [comment]
@zhicheng-ning 志成飞速的将看板完成了一个[初版的设计](http://113.31.109.198/#/delink?link=a2G5RVchmI%2B0fGZ8Xh8HaQu1nz%2FXwOsKRb0tYDHt%2FLoe5lTA6TRcgmXpm73lRokq4TfCm0pDKQESNaHfCn%2FHwA&user=VAU%2BlNqEIu0MrqtAhqCNZ%2BNibGJPYkBJ%2BFRtOp%2B81IA5A0fYcUeaXsVKorhvwSmrSCS11%2F00%2B8c%2BxYGa4EtXZg)，接下来就可以做些优化了：


![image](https://user-images.githubusercontent.com/15010826/199664062-99983f5a-11c0-46f1-b6fc-d21524461c71.png)

**Comment by will-ww** [comment]
我有几个可以优化的地方，特别为可以充分参考咱们的 Hypercrx 开源项目的内容：

![image](https://user-images.githubusercontent.com/15010826/199664899-8877dcd3-05a7-4f28-b544-f96802968c3e.png)

**Comment by zhicheng-ning** [comment]
这个是加入了活跃度和影响力榜单的版本

![image](https://user-images.githubusercontent.com/39022409/199680246-4487f0b3-f6dc-47ae-be1c-575019f590f0.png)

**Comment by zhicheng-ning** [comment]
两个版本：
- http://113.31.109.198/link/0alHmGAO
- http://113.31.109.198/link/3qNZ0sCL

**Comment by will-ww** [comment]
> 两个版本：
> 
> * http://113.31.109.198/link/0alHmGAO
> * http://113.31.109.198/link/3qNZ0sCL

超级棒，我去问问木兰社区的用户，提提建议~

**Comment by gh-Devin** [comment]
似乎第二个可以，用第二个吧：）
