### ISSUE TITLE
【数据支持】2022中国开源年度报告数据篇支持

### ISSUE THREAD

**Issue by xgdyp** [X-lab2017/open-wonderland#226]
hello各位小伙伴们，又到了准备开源年报的时间。中国开源年度报告是由开源发起的，从多个角度呈现中国开源发展情况的报告。2022年的报告共分为开源大事记篇、开源数据篇、开源商业篇、开源洞察篇四个篇章。
我们实验室将和gitee、devlake的小伙伴共同完成数据篇的相关工作。包括指标的开发和结果的展示撰写。
今天数据篇的提纲如下：

### 宏观洞察：
1. 活跃度影响力指标介绍
2. 基于指标实现的数据
- 世界影响力排名 Top 10
- 中国影响力排名 Top 30
- 中国企业开源数据分析
- 中国开发者年度榜单
- Apache、CNCF、LF 中国项目影响力
- 领域项目影响力分析（包括数据库、操作系统、前端、云原生（CNCF）、大数据）

### 项目洞察篇：
1. 项目中的机器人行为识别和判断，并介绍总结机器人对于开源项目的影响（Devlake负责）
2. 对于OpenRank入围2022年度前100的项目，对其进行深入分析，探究社区增长和事务（Issue、PR）处理情况相关指标（Devlake负责）
- 新贡献者、离开人数、第一次关闭issue人数（Devlake负责）
- Issue响应天数、PR响应天数、第一次响应Issue时间（Devlake负责）
3. Devlake企业版对于开源软件的分析（Devlake负责）
- 研发效能指标含义（Devlake负责）
- 榜单（Devlake负责）
- 结论解读（Devlake负责）
4. 开源项目时区打点分布图
## Gitee篇：（Gitee负责）
- 概述
- 总体语言趋势
- 增速最快的语言
- 新增开源项目领域分布
- 年度最受欢迎的开发者
- 年度最受欢迎的组织
- Gitee指数介绍、Gitee指数top10（有变化 列计算方式）
- 开源与合规
- 总结

对我们实验室来说，我们主要是通过Opendigger实现宏观洞察、以及项目洞察中的时区分布图
这里对于我们要实现的内容进行说明：
1. 每项任务需要交付榜单表格，以及榜单对应的文字说明。文字说明包括榜单的数据分布、展示的趋势等。
2. 榜单是根据OpenRank进行排序，但是展示的内容不仅包括OpenRank，还可以包括组成OpenRank的因素，活跃度、star数、fork数等指标
3. 领域项目影响力分析，可以通过图表的形式进行展示
4. 大部分指标OpenDigger都已经实现，我们只需要按照交付格式来做即可
5. 如果大家有更好的指标或分析内容放到年报上，或者有疑问，我们可以在issue下讨论

**Comment by xgdyp** [comment]
@will-ww 王老师这边还有什么要补充的内容嘛～

**Comment by will-ww** [comment]
> @will-ww 王老师这边还有什么要补充的内容嘛～

有不少，晚点我统一发出来哈~

**Comment by will-ww** [comment]
有几个补充建议，大家看看：

宏观洞察篇中：
- 补充[技术领域](https://github.com/X-lab2017/open-digger/tree/master/labeled_data/application_domain)的分析（建议@PureNatural 负责）
- 领域项目影响力分析（建议@birdflyi 负责）

项目洞察篇中：
- 补充全球与中国的 COSS 项目发展分析，具体[参见这里](https://github.com/X-lab2017/open-digger/blob/master/notebook/coss.ipynb)

已有部分的内容，好的内容尽量也都放进去：

- [2022 中国开源年度报告](https://github.com/X-lab2017/open-digger/blob/master/notebook/China_open_source_report_2022.ipynb)
- [2022 中国开源发展蓝皮书](https://github.com/X-lab2017/open-digger/blob/master/notebook/China_open_source_blue_paper_2022.ipynb)

其他的内容大家可以补充，然后分工，争取一周后，咱们提交~

**Comment by PureNatural** [comment]
ok, 我近两三天会做相应的补充～
