### ISSUE TITLE
[阶段性总结] 华师 & DataEase 合作双周会议：2023-01-10

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-wonderland#234]
# 2022 下半年阶段性总结会议

- 时间：12:00 ~ 13:00，2022/01/10
- 腾讯会议：343-2753-3413 （[入会链接](https://meeting.tencent.com/dm/GN3XlDq5TFPR)）

# 议题
**0. 总结**
- 总体介绍：王老师
- 计算机应用能力大赛总结：蒲老师
- 基于DataEase的课件：曾老师
- 飞致云 DataEase：飞鸽 @xueqidove
- 开源可视化大屏：@zhicheng-ning

**1. 基于 DataEase 工具的课程资源建设与教学实践**
- [x] 计算机公共课资源建设（曾老师）
- [x] 数据科学与工程导论资源建设（@xgdyp ） 
- [x] “计算机应用能力大赛”中“信息可视化设计”（@tvbboy ）
- [x] 数据科学与工程导论（@will-ww）

**2. 基于 DataEase 的开源社区可视化分析**
- [x] #211
- [x] [X-lab 开放实验室 XSOSI 大屏](http://dataease.nzcer.cn/link/E1OQKVBz)（@zhicheng-ning）
- [x] [OpenLeaderboard 项目洞察大屏](http://dataease.nzcer.cn/link/LeMILNSw?attachParams=eyJvcmdfbmFtZSI6IlgtbGFiMjAxNyIsInJlcG9fbmFtZSI6Im9wZW4tZGlnZ2VyIiwidF9tb250aCI6IjIwMjItMTItMDEifQ==)（@zhicheng-ning）

**3. 宣传活动与渠道**
- [x] [2022 CCF中国开源大会](http://chinaosc.ccf.org.cn/)， 11月5日（本周六）下午，木兰分论坛-[微信推文链接](https://mp.weixin.qq.com/s/Kf6HmSvbUhGixcvVgsCcGA)
- [x] CCF 中国软件大会 [ChinaSoft](http://chinasoft.ccf.org.cn/)（11月25日）
- [x] CNCC 2022 开源人才培养论坛（12月08日）
- [x] 新思科技OSPO及开源治理实践论坛（12月21日）
- [x] 木兰峰会-开源治理论坛（12月30日）

**4. 后续发展机会**
- [ ] [基于 DataEase 发布 GitHub 2022 洞察报告](https://github.com/X-lab2017/open-wonderland/issues/232)
- [ ] 水杉在线平台中是否需要添加一门可视化的课程
- [ ] 合作共同出版相关书籍

**Comment by zhicheng-ning** [comment]
# 成果展示
- 木兰开源社区治理大屏

![image](https://user-images.githubusercontent.com/39022409/211272404-31894443-bac8-4dea-b050-bdd395e53695.png)

- X-lab 开放实验室 XSOSI 大屏

![image](https://user-images.githubusercontent.com/39022409/211282924-625de324-71ce-4dd4-81e3-c78ba2907e10.png)


- OpenLeaderBoard 项目洞察大屏

![image](https://user-images.githubusercontent.com/39022409/211283392-0a577b91-f560-4b2b-bec3-61011e388b7c.png)

![image](https://user-images.githubusercontent.com/39022409/211284854-ffb21134-e302-4536-913b-28cb89f73dfa.png)

**Comment by will-ww** [comment]
# 部分宣传页面展示

- 2022 木兰峰会

![image](https://user-images.githubusercontent.com/15010826/211428633-c929df6e-220e-47d9-bd48-c874200403e5.png)

- CNCC 开源人才培养论坛

![image](https://user-images.githubusercontent.com/15010826/211428832-66771003-debf-4623-ae00-7e877d12b94b.png)

-  新思科技OSPO及开源治理实践论坛

![image](https://user-images.githubusercontent.com/15010826/211428995-e5c317ea-ee83-4859-b04e-37cea9840fe3.png)

**Comment by will-ww** [comment]
再给大家推荐一本书籍，一个不错的参考：《[商业仪表盘可视化解决方案](https://item.jd.com/12722724.html)》

英文版是 Amazon 上的畅销书，[链接](https://www.amazon.com/Big-Book-Dashboards-Visualizing-Real-World/dp/1119282713/ref=sr_1_1?keywords=The+Big+Book+of+Dashboards&qid=1673323980&sr=8-1)~

![image](https://user-images.githubusercontent.com/15010826/211460890-6bc9ad9e-8189-4154-8c13-72e843fa49e7.png)

**Comment by will-ww** [comment]
补充一个上学期，学生在《数据科学与工程导论》课程大作业中的一个作品片段：

![d6eaf70327c39d704922049600b8d13](https://user-images.githubusercontent.com/15010826/215385141-60491ac2-d475-4319-b144-7afb45fdfa69.png)
