### ISSUE TITLE
DE-GitHub-1 全球增长大屏（夏小雅）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#243]

**Comment by will-ww** [comment]
已有基础：
- http://edu.dataease.fit2cloud.com/link/o421W9LB
- GitHub_2020_数字洞察报告
- [Open Source Highlights: Trends and Insights from GitHub 2022](https://ossinsight.io/blog/trends-and-insights-from-github-2022/)

**Comment by will-ww** [comment]
我个人希望了解的一些信息包括：

1、当前的一些重要指标
- 可以参考上面的“2022年度报告”大屏

2、一些趋势分析（例如近五年的，或者用户可以自定义调节）
- GitHub全域事件数总数趋势
- GitHub活跃仓库总数趋势
- GitHub活跃开发者总数趋势
- 排名前 10000 项目的总体活跃度趋势
- 排名前10000 项目的 OpenRank 趋势
- 排名前 5000 的开发者活跃度趋势
- 排名前 5000 的开发者 OpenRank 趋势
- 全域 OpenRank Top 10（项目、企业、开发者、机器人）

等等，应该还挺多，也可以考虑你那篇论文的逻辑：Exploring Activity and Contributors on GitHub Who, What, When, and Where~

~ @xiaoya-yaya

**Comment by xiaoya-yaya** [comment]
![WX20230305-150845@2x](https://user-images.githubusercontent.com/56542972/222946832-94565280-c16e-4790-9781-92caf5632f67.png)

**Comment by xiaoya-yaya** [comment]
示例 demo 如上图，包含：
* 全域 OpenRank Top10 开发者榜单、项目榜单
* Top 10000 项目的活跃度、OpenRank 趋势
* Top 5000 开发者的活跃度、OpenRank 趋势
* 编程语言变化趋势
* 开发者工作时间（活跃时间）分布
* 开发者和机器人在不同行为类型上的分布对比

**Comment by will-ww** [comment]
So cool~
