### ISSUE TITLE
DE-GitHub-2 区域对比大屏（黄温瑞、宁志成）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#244]

**Comment by zhicheng-ning** [comment]
初步设计稿如下图：

![image](https://user-images.githubusercontent.com/39022409/222906538-7d4caf39-29cc-4b3c-91d7-175f57d9975b.png)

主要包含的数据项：
- 世界地图/项目地域分布（展示各个国家/地区/大洲的项目数量）
- 各地区 OpenRank 占比分布
- 国内外开源项目数量对比
- 开源项目数量/指标走势
- 中国开源项目领域分布 
- 美国开源项目领域分布
- 中美开源项目对比
- 各国家/地区中各个事件数量的表格对比

欢迎大家补充~

**Comment by will-ww** [comment]
Cool~

**Comment by zhicheng-ning** [comment]
在向 OpenDigger 了解情况后，发现地区对比这部分的数据大概率是不好做的

**Comment by zhicheng-ning** [comment]
- [x] 开发者地域分布 
- [ ] xxx
- [ ] xxx
持续更新...... @andyhuang18

**Comment by andyhuang18** [comment]
<a href='https://dataease.nzcer.cn/link/jSsz05OM'>区域对比大屏</a>已经做好了，大家还有什么建议可以告诉我~

![536c00e60db6148eed8ec900ee678c0](https://user-images.githubusercontent.com/50283262/236823237-d59e938a-43b6-4e27-9bad-da22fd951a34.png)
