### ISSUE TITLE
DE-GitHub-3 供应链大屏（毕枫林、伍泰炜）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#245]

**Comment by will-ww** [comment]
目前实验室采集了部分供应链的数据：http://data-status.x-lab.info/

前面也讨论过部分外部信息：https://github.com/X-lab2017/open-wonderland/discussions/230

中科院的供应链前期积累：参照相关论文

[孙晴_2030785_电子与信息工程学院_基于开源软件维护性特征的开源软件供应链风险预测方法研究.pdf](https://github.com/X-lab2017/open-wonderland/files/10847381/_2030785_._.pdf)

供应链是个非常不错的视角，基于编程语言的一种划分，同时也能形成依赖网络。

**Comment by bifenglin** [comment]
数据集讨论：
1. 目前我们已有的与供应链相关数据为GH archive数据（包含github 协作行为日志数据），Library.io的数据（制品库数据），目前可以基于以上数据进行分析设计。
2. 我认为还可以收集的数据为 https://deps.dev/ 的数据，包含依赖关系  
<img width="1901" alt="image" src="https://user-images.githubusercontent.com/15813364/221747306-06439ce7-4109-49cc-8d45-9c22f8eca57c.png">
和 https://osv.dev/ 的数据，包含漏洞数据   
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/15813364/222023724-49ab1605-eead-4dcf-bf9b-1ee153adb575.png">

其中osv的讨论如 #230 
library.io数据在 http://data-status.x-lab.info/ 

基于此，我们目前可以考虑的指标可以有   
1. 依赖所有的包，参与依赖包的人数，总提交数等求和信息。  
2. 包更新频率、包发布频率时序信息，再加上不同制品库数量的比例，不同制品库之间的人数对比等对比信息。  
3. 包的活跃度排名，影响力排名等排名信息
4. 包的开发者人员地域信息

**Comment by will-ww** [comment]
OSSI 开源安全工具指数：[链接](https://mp.weixin.qq.com/s?src=11&timestamp=1677995228&ver=4387&signature=Tm3qKhlgTevNNRMruu5HHwXv81NFLCwB0OCvtIp0I7qNAai0U2nHv*PRrSYQmLP0mKuKBMha0ZE2xpBHm1U5Gb86qdB-BuUiZ9piYcMxrjpvLVWd*OKKsbMk228VuIBN&new=1)

**Comment by bifenglin** [comment]
> OSSI 开源安全工具指数：[链接](https://mp.weixin.qq.com/s?src=11&timestamp=1677995228&ver=4387&signature=Tm3qKhlgTevNNRMruu5HHwXv81NFLCwB0OCvtIp0I7qNAai0U2nHv*PRrSYQmLP0mKuKBMha0ZE2xpBHm1U5Gb86qdB-BuUiZ9piYcMxrjpvLVWd*OKKsbMk228VuIBN&new=1)

该链接已失效。

**Comment by will-ww** [comment]
> OSSI 开源安全工具指数

Google一下：https://www.secrss.com/articles/51844

**Comment by bifenglin** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15813364/223313751-516f4f40-c640-4764-b94a-0a0619484d5b.png">

**Comment by bifenglin** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/15813364/223313898-5c0feb2a-eef9-4a59-b8c5-46a92c9ff017.png">

**Comment by bifenglin** [comment]
示例如上，包含：
1. 制品库统计信息
2. License使用情况
3. 漏洞总量、供应链项目总量、语言总量、License总量
4. 最受欢迎的语言排名
5. Top安全项目指数
6. Top安全项目的watcher与contributor
7. 软件供应链根据语言进行的统计信息

**Comment by bifenglin** [comment]
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/15813364/224483349-a1cfde44-22a8-459c-8672-6fb4cc5d3071.png">
样式优化与指标修改的最新版本，看看大家有什么建议

**Comment by bifenglin** [comment]
https://www.cert.org.cn/publish/main/upload/File/2021%20Risk%20Analysis%20Report%20of%20Open%20Source%20Software%20%20.pdf

**Comment by bifenglin** [comment]
部分数据来自：
-  https://deps.dev/ 
- https://osv.dev
- https://www.cert.org.cn/publish/main/upload/File/2021%20Risk%20Analysis%20Report%20of%20Open%20Source%20Software%20%20.pdf
