### ISSUE TITLE
DE-GitHub-4 技术领域与语言大屏（韩凡宇）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#246]
@PureNatural

**Comment by PureNatural** [comment]
我查阅了之前发布的开源年报以及王老师提到的[OSSInsight](https://ossinsight.io/2022/)做的总结报告，

认为关于技术领域与语言大屏的设计可以包含以下几点：

a.四大技术领域（云原生、大数据、数据库和操作系统）的趋势发展情况，一个折线图。（技术领域维度）

b.四大技术领域下的项目趋势发展情况，一共四个趋势折线图。（项目维度）

c.近几年编程语言的排名趋势图，参考图如下：
<img width="586" alt="image" src="https://user-images.githubusercontent.com/29674550/222461852-1f5cce47-2f2d-4025-950a-c8bf45a0c0b5.png">

d.2022年全域开发者语言榜及各个语言所占比例（列表和饼状图），示例图如下：
<img width="393" alt="image" src="https://user-images.githubusercontent.com/29674550/222462868-b27a1a0c-1531-4c35-8706-7ff095989219.png">

e. 技术领域与编程语言交叉分析，之前开源年报没有相关内容，我的想法是分析各个技术领域对应的编程语言趋势发展情况，例如大数据可以由java、python等多种编程语言支持，我想得出近几年大数据这个领域下，java、python和其它语言的走势情况，从而可以得出具体哪一门语言针对大数据领域逐渐占主导地位。(四大技术领域，四个折线图)

以上5个可视化组件，a和b为技术领域可视化内容，可以布局在左侧，e为交叉分析内容放中间，c和d放最右侧。

关于数据：

a.技术领域的相关数据[open-digger](https://github.com/X-lab2017/open-digger)已经提供。

b.关于编程语言的数据应该也有，但我没有找到具体数据源，如果@zhicheng-ning 同学有了解的话，可以提供一下不，非常感谢～

**Comment by will-ww** [comment]
我能够想到的几个包括：

五大领域中的项目（当下信息）：
- 每类项目数的总量信息、占比信息
- 每一类别中所有项目的活跃度与OpenRank加总信息、加总后的占比信息、对比分析

五大领域中的项目（趋势信息）：
其实也想知道下这五类领域中项目的趋势信息，但因为 10000 榜单，每年会有变化，不知道有什么好的近似的方法。例如，想知道：
- 这五类占比的近五年变化趋势，哪一类逐年增长（感觉non_software类在增长）、哪一类逐年下降
- 同时用活跃度和OpenRank去分析

technology 下面的标签，就可以选几个相对成熟的技术领域进行展示了。

**Comment by PureNatural** [comment]
我之前按照technology标签下的项目数据整合了大屏，先发出来，我在今天跑出来新的数据后，随即按新的五大领域的统计结果进行展示替换，今天晚些发出来。
![WX20230306-154318@2x](https://user-images.githubusercontent.com/29674550/223048266-738000f5-65d3-48d3-a4dd-585d6c2b82d9.png)

**Comment by zhicheng-ning** [comment]
> 关于编程语言的数据应该也有，但我没有找到具体数据源

这部分数据在 clickhouse 数据库里应该有

**Comment by PureNatural** [comment]
![image](https://user-images.githubusercontent.com/29674550/223110210-9e3bac18-f1f2-4f22-8790-97f0eaa5aa62.png)

初步设计如上图，包含以下内容：

- 五大领域项目数量占比图
- 各个领域中所有项目的活跃度与OpenRank加总信息及加总后的占比信息
- 近五年各领域活跃度与OpenRank的增长趋势
- 近五年各领域活跃度与OpenRank占当年五大领域总和的百分比增长趋势
- 编程语言榜
- 编程语言变化趋势
- 2021-2022编程语言增长率

按照近五年各领域活跃度与OpenRank占当年五大领域总和的百分比增长趋势，non software的占比确实在增长，虽然涨幅较小。
考虑到10000榜单会有变化，我可以每年年初或年底重新获取一次榜单，这样方便未来对项目各方面展开分析。重新获取榜单后，也要对新进入的项目重新打标签。

**Comment by xgdyp** [comment]
![image](https://user-images.githubusercontent.com/37795442/223297869-6048bc42-de28-49d7-abdf-b70677be4124.png)
数据库中有一个 repo language 字段

**Comment by PureNatural** [comment]
根据上次开会提出的建议，总体设计布局不变，左上角两个柱状图替换为折线图。改动后效果如下：
![image](https://user-images.githubusercontent.com/29674550/223611287-4d11e06b-1cf0-4653-b67d-5d3565d84c50.png)
