### ISSUE TITLE
DE-GitHub-5 数据库领域大屏（娄泽华）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#247]

**Comment by will-ww** [comment]
因为数据库领域的标签数据质量还不错，应该可以有不错的洞见。

可以有总体排名：用OpenRank和活跃度，可以有二级列别（选几个重点类别）下的排名。

开源象限(OpenQuadrant) 之类的是不是也可以用上。

去年云栖上的“[开源大数据热力报告](https://blog.csdn.net/xiangwang2206/article/details/127780891)”也是个不错的参考~

**Comment by PureNatural** [comment]
![image](https://user-images.githubusercontent.com/29674550/224481468-28b62c54-3bea-4b83-b204-4c382071352d.png)
数据库领域大屏设计如图，可视化组件介绍如下：

- 左一展示了2018-2022年TOP5数据库的openrank变化趋势。
- 左二为2022年数据库openrank榜单。
- 左三为2022年数据库各子领域下的openrank对比柱状图。
- 中上是观察其他组件得出的结论。
- 中下为2018-2022数据库各子领域下的openrank和活跃度的变化趋势。
- 右边的组件和左边的类似，指标替换为活跃度。

通过可视化效果可以看出

- clickhouse在2022年超越了elasticsearch，双指标排名第一
- elasticsearch活跃度与openrank连年下降
- spark的openrank连年下降
- trino双指标增长迅速（2018年指标值都为0）
- 关系型数据库的openrank和活跃度连年排名第一且逐渐拉开和第二名的差距
- 时序型数据库发展较快，从2018年的第5增长到2022年的第3，且逐渐缩小与第2名的差距

**Comment by birdflyi** [comment]
补充材料：
[colnames_mapping.csv](https://github.com/X-lab2017/open-wonderland/files/10948504/colnames_mapping.csv)

其他可以获得的特征：
字段：

|tables|colname1|colname2|colname3|colname4|colname5|colname6|colname7|colname8|colname9|colname10|colname11|colname12|colname13|colname14|colname15|
|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|----|
|[**DB-Engines**](https://github.com/birdflyi/db_engines_ranking_table_crawling/blob/main/data/db_engines_ranking_table_full/ranking_crawling_202302_automerged.csv)|DBMS|Data_Model_mapping|Written in|Query Interface|System Architecture|Developer|Country of Origin|Start Year|End Year|Project Type|Licenses|github_repo_link|open_source_license|||
|[**dbdb.io**](https://github.com/birdflyi/dbdbio_OSDB_info_crawling/blob/main/data/dbdbio_OSDB_list/OSDB_info_202302_joined.csv)|DBMS|category_label||||Developer||initial_release_recalc|current_release_recalc||License_info|github_repo_link|open_source_license|Score_Feb-2023|Rank_Feb-2023|
|**merged_table**|DBMS|category_label|Written in|Query Interface|System Architecture|Developer|Country of Origin|initial_release_year|current_release_year|Project Type|License_info|github_repo_link|open_source_license|Score_Feb-2023|Rank_Feb-2023|


理论上这些都是可以获取的：
- 数据库领域总体特征统计（项目数）：各模型项目数占比（饼图）、地区总体活跃度统计（地理着色）、各模型活跃项目平均年龄（柱状图）、总体使用语言（饼图）、总体使用Licenses（饼图）
- 数据库领域topK项目排行：openRank
- 数据库领域协作趋势：总体日志数、活跃仓库数、活跃开发者数
- 特别地：
	- 地区内总体活跃度环比增长率Top1（不区分模型类型-渐变着色，区分模型类型-多着色）
	- 各模型的总体日志数增长率趋势图
	- 各Licenses项目数趋势图
		
- 其他可能的参考：https://blog.csdn.net/xiangwang2206/article/details/127780891 如topk数据库逐年热力图像

**Comment by birdflyi** [comment]
以上信息基本实现了自动化爬取，并且根据`github_repo_link`字段向opendigger中提交了[issues#1136](https://github.com/X-lab2017/open-digger/issues/1136)及[issues#1093](https://github.com/X-lab2017/open-digger/issues/1093)，获取了相应的repo_id, 可以作为大屏需要展示的信息的主要样本数据集@PureNatural

**Comment by PureNatural** [comment]
初版设计趋势图太多，统计图太少，故基于上述提供的特征，后续对设计进一步优化～

**Comment by PureNatural** [comment]
![image](https://user-images.githubusercontent.com/29674550/224530252-193f32a6-d3cd-4519-82b1-3c9116b59922.png)

新增了三个饼图：

- 数据库子领域项目数占比（关系型数据库占比最大）
- 数据库license项目占比（license项目已超过50%）
- 数据库开发语言占比（以java和C++为主）

特征较多，选取部分统计项进行展示。

**Comment by birdflyi** [comment]
All of the Open Source DBMS which have a github repo link by 2023-03-31 is available here:  [dbfeatfusion_records_202303_automerged_manulabeled.csv](https://github.com/birdflyi/db_feature_data_fusion/blob/main/data/manulabeled/dbfeatfusion_records_202303_automerged_manulabeled.csv).
The data is fused from [dbdb.io](https://dbdb.io/) and [DB-Engines](https://db-engines.com/en/ranking), and has been partial manu-labeled. Welcome to create issues in [db_feature_data_fusion](https://github.com/birdflyi/db_feature_data_fusion).
