### ISSUE TITLE
DE-GitHub-6 基金会开源大屏（张欣然）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#248]

**Comment by longyanz** [comment]
初步设计稿如下：

![image](https://user-images.githubusercontent.com/91717658/223049227-833823e7-035e-4eef-8b13-26c61d2e02ad.png)

大屏所需的数据有：

- apache基金会项目数量，委员会数量（可从https://apache.org/ 获取）
- 仓库数量
- 开发者数量，star数，fork数等指标
- 贡献者月度活跃度/影响力
- 仓库月度活跃度/影响力
- 项目月度活跃度，并显示项目包括的仓库的活跃度分布
- 项目/仓库语言分布
- 项目/仓库类别分布
- 开发者/Issue/PR 数量变化图

关于Apache的项目和仓库定义，我的理解中一个项目可以包含多个仓库，如：

![image](https://user-images.githubusercontent.com/91717658/223052460-8f4be8b8-a38d-4ac1-8961-cbc719d2425c.png)

截图中的三个仓库都属于echarts项目。
欢迎大家补充~

**Comment by longyanz** [comment]
更新了一版Apache基金会的大屏，去掉了一些不太好获取的数据，修改了一下排版，可以在下周的会议上讨论~
![1680764505963](https://user-images.githubusercontent.com/91717658/230296791-225ef48b-675e-435b-8fb4-74ce47c0d7d8.png)
