### ISSUE TITLE
DE-GitHub-8 X-lab OSPO 大屏（唐烨男）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#250]

**Comment by tyn1998** [comment]
开始想了些Idea，但是发现好像和OSPO的关系不大 😆 ，最后选择copy了Frank学长之前用DataV做的[大屏](http://dashboard-overview.opensource-service.com/?label=xlab)。示意图如图所示：

![X-lab OSPO 大屏设计示意图](https://user-images.githubusercontent.com/32434520/222960677-bc6b0911-58c5-4997-9f18-985522827dc0.png)

**Comment by will-ww** [comment]
是这个意思，其实就是把DataV做的[大屏](http://dashboard-overview.opensource-service.com/?label=xlab)和XSOSI大屏，进行一个有机的结合。从实验室管理的视角看，咱们的项目、开发者等发展如何。可以再优化下~

**Comment by tyn1998** [comment]
**设计思路**：

- 尽量不重复其他大屏的已有工作
- 尽量展示聚合信息

**预期效果**：

![X-lab OSPO 大屏设计示意图 (1)](https://user-images.githubusercontent.com/32434520/223095639-0a01e3b2-cd93-46ae-818c-3ec6384660d8.jpg)

**其他说明**：

- 左边项目区域支持月份切换；右侧的语雀和学术成果总是展示最新（因为数据不支持）
- 语雀部分的统计展示可以不按语雀官方的设计来
- 项目区域还可以加个许可证统计的饼图

**Comment by tyn1998** [comment]
## 能够落实的新设计

结合了DE的特性以及可用的数据来源又设计了一次，确保所有图表都是能实现的。由于DE必须要先有数据，才能编辑图表，但是将数据处理成期望的格式并实现自动化方案我不是很擅长，所以先手绘了一个图。

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/32434520/231044140-c279a5d6-14c6-4e9b-885d-a9795a9413a5.png">

可以看到一个有5个红框，5个红框会对应5张DE的数据表。左2/3区域是参加XSOSI的项目看板（支持选择月份查看），右1/3区域分别展示了X-lab语雀看板和论文发表列表（不能选月份，只呈现最新情况）。

左边的“Repo明细”会将OpenDigger目前已经导出的大多数[指标](https://github.com/X-lab2017/open-digger#metrics-or-indices-usage)都放到一个DE明细表中，这也许不Fancy，但应该会很实用的，因为DE明细表还支持点击列头升序降序排列。

“OpenRank明细”会分成一个饼图和矩形树图。饼图的每一块是对应仓库当月的全域OpenRank值，点击饼图的某块会联动右边的矩形树图。矩形树图分为两级，第一级展示各个开发者（包括外部贡献者）的项目内OpenRank值，第二级展示某个开发者的项目内OpenRank值的构成。

语雀的空间统计数据可以通过HTTP请求拿到，只要先在浏览器登录拿到session，然后带上这个session请求就可以了，有自动化的空间。

论文发表情况需要手工整理。

## Todo

- [ ] 落实5个数据表的表结构（每个表需要哪些字段）
- [ ] 确定5个数据表的字段需要哪些数据源
- [ ] 写代码，向数据源请求数据，处理数据，导出5个Excel格式的数据表（后序迭代，尽量做到自动化）
- [ ] 在DE导入5个数据表，然后开始拖拉拽做大屏

**Comment by will-ww** [comment]
So cool~
