### ISSUE TITLE
DE-GitHub-9 开源项目社区大屏（宁志成）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#251]

**Comment by zhicheng-ning** [comment]
项目大屏这部分可以等 DE 那边再出一版稿子（上次单周会议讲过的）~

**Comment by zhicheng-ning** [comment]
[项目大屏链接](https://dataease.nzcer.cn/link/dqMbZrBk?attachParams=eyJvcmdfbmFtZSI6ImRhdGFlYXNlIiwicmVwb19uYW1lIjoiZGF0YWVhc2UiLCJ0X21vbnRoIjoiMjAyMy0wMS0wMSJ9)

![image](https://user-images.githubusercontent.com/39022409/224608932-7c384863-e29e-49dc-a938-ecf17731bfdc.png)

**Comment by zhicheng-ning** [comment]
已完成
