### ISSUE TITLE
DE-GitHub-10 项目 DevOps 或开发者大屏（张翔宇）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#252]

**Comment by will-ww** [comment]
建议 @xgdyp 做一个开发者大屏，然后连接到 OpenLeaderboard 上面去~

![image](https://user-images.githubusercontent.com/15010826/222936857-197300bf-65c1-42ef-8ec6-1bed3b2460be.png)

**Comment by xgdyp** [comment]
# Developer Insights
## 开发者贡献时间分析

- ContributionCalendar

![img](https://cdn.nlark.com/yuque/0/2023/png/21501894/1678151804660-cef854e1-9a90-4644-92ac-b1bd7f5178d2.png)

- Active Days

一年中共在GitHub上活跃多久

- Contribution by hour/by day
- events type
- Longest Streak/Longest Gap /Weekend(Workday) Activity

## 开发者贡献内容分析

- 开发者贡献语言分布、仓库分布

贡献语言有多种算法：根据LOC、根据PR、根据自己star项目的语言分布

![img](https://cdn.nlark.com/yuque/0/2023/png/21501894/1678104875403-fc0c6062-0ef6-4899-b2a6-b812c4da4278.png)

- 开发者潜在技能

根据其参与到的项目所用的技能进行分析（需要code scan 审查一些特定的工具）

- 开发者GitHub Stats

![img](https://cdn.nlark.com/yuque/0/2023/png/21501894/1678104896718-9cfb2272-6a88-4a75-9611-272ec029c3e8.png)

- 开发者贡献时间分布图
- 开发者贡献语言量
- 活跃项目网络

![img](https://cdn.nlark.com/yuque/0/2023/png/21501894/1678152583232-832bc603-9177-4852-a432-ecf165fef705.png)

## 开发者OpenRank Activity（核心数据）

![img](https://cdn.nlark.com/yuque/0/2023/png/21501894/1678104985005-a016c538-305d-45fc-a019-2b2872bc8fa1.png)

## 开发者社交网络分析



- 项目协作网络

![img](https://cdn.nlark.com/yuque/0/2023/png/21501894/1678152539308-b3a31d68-ddd3-4c44-b085-46096f9be0c8.png)

- 开发者协作网络
- Org中贡献者占比

**Comment by xgdyp** [comment]
@will-ww  我把我能想到的指标都列了出来，有些可能要走GitHub API～

**Comment by will-ww** [comment]
> @will-ww 我把我能想到的指标都列了出来，有些可能要走GitHub API～

首先，你需要拼成一个大屏；其次，需要做点创新，目前都是已有的东西~ @xgdyp
