### ISSUE TITLE
Dev.Together 2022 开发者生态峰会筹备（3月10日前提交）

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-wonderland#253]
[百宝箱市集参展准备要求文档](https://sifou.feishu.cn/docx/GA8SdLuF7oTJiBxUdvpcs91Bnxe)：

- [x] logo提交
- [x] 展位设计文件
- [x] 展位打卡护照设计文件

**Comment by will-ww** [comment]
> 供大屏展板（可上网）吗，还是说我们提供各类大屏的图片给

前面说过可以提供电视的，可以问他们核对下~

**Comment by xgdyp** [comment]
展位设计文件是指类似于易拉宝之类的吗

**Comment by xgdyp** [comment]
<img width="484" alt="image" src="https://user-images.githubusercontent.com/37795442/222958922-28dee1d4-df7c-4542-9e0a-fc17e34a6683.png">
@will-ww @tyn1998 @zhicheng-ning  大家觉得展板这样设计怎么样？

**Comment by xgdyp** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/37795442/222959062-1915f53b-c609-4d70-847b-2a191ad1d1fd.png">

**Comment by zhicheng-ning** [comment]
左上角可以换成 xlab logo （小灯泡）
