### ISSUE TITLE
收集 GitHub Access Token

### ISSUE THREAD

**Issue by zhicheng-ning** [X-lab2017/open-wonderland#255]
- 背景：目前 DataEase 大屏中需要使用到 GitHub API 每天定时获取项目的 star 和 fork 数，但是限于单个 token 每小时的请求次数限制，所以希望大家能帮忙提供 GitHub API 的 token （不需要提供任何权限，保证安全）。详细参考：https://github.com/X-lab2017/od-api/issues/14

- 如何创建 GitHub token：https://github.com/X-lab2017/od-api/issues/19

**Comment by zhicheng-ning** [comment]
Thanks for @tyn1998 @Zzzzzhuzhiwei ！！！

**Comment by xiaoya-yaya** [comment]
已发送token，想问一下：

- 获取 star 和 fork 数的项目范围是什么，是 opendigger 下的所有标签数据的项目吗？

**Comment by zhicheng-ning** [comment]
> * 获取 star 和 fork 数的项目范围是什么，是 opendigger 下的所有标签数据的项目吗？

OpenLeaderBoard “项目” 中所有排行榜前三百的项目
