### ISSUE TITLE
[活动] X-lab2017下的项目会参加Summer2022吗？截止申请还有11天

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-wonderland#26]
如题~

**Comment by xiaoya-Esther** [comment]
#### Proposal
OpenDigger 可以申报一个 - 在 Jupyter lab 环境中实现部分 CHAOSS Metrics，具体参考 Open Digger 仓库下的 [[Metrics] open issues](https://github.com/X-lab2017/open-digger/issues)~

**Comment by tyn1998** [comment]
OpenGalaxy起码可以有：
- https://github.com/X-lab2017/open-galaxy/issues/20
- https://github.com/X-lab2017/open-galaxy/issues/29

**Comment by will-ww** [comment]
> #### Proposal
> OpenDigger 可以申报一个 - 在 Jupyter lab 环境中实现部分 CHAOSS Metrics，具体参考 Open Digger 仓库下的 [[Metrics] open issues](https://github.com/X-lab2017/open-digger/issues)~

支持！

**Comment by gymgym1212** [comment]
好呀～感觉有很多工作可以做起来

**Comment by gymgym1212** [comment]
实验室项目的 Summer2022 都申请上了，这个 issue 就关了吧
