### ISSUE TITLE
初赛知识问答的出题工作 @will-ww

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#266]

**Comment by will-ww** [comment]
初赛的问答题，除了前六讲总共 7 * 6 = 42 题目外，加上如下 8 道题目，即为 50 道题目：

1. 作为当今全球数字化转型下的创新驱动力，以下哪个是最为重要的：
A. 云原生与开源（X）
B. 生产关系
C. 生产力
D. 自由市场

2. 全球开源的普世价值观，包括：
A. 自由与开放
B. 对等与协作
C. 
D. 以上所有（X）

3. 关于开源教育下列说法哪个正确：
A. 有利于提升全民的整体数字化创新力
B. 不仅仅和计算机类专业相关，本质上是一个跨学科的内涵
C. 有利于推动教育的数字化转型
D. 以上所有（X）

4. 下列哪个开源基金会是在我国成立的：
A. Apache 软件基金会
B. Linux 基金会
C. 开放原子开源基金会（X）
D. 中国教育发展基金会

5. 开源社区的“开发者”一般指什么人群：
A. 开源项目的用户群体
B. 开源项目的贡献者群体
C. 开源项目的维护者群体
D.  以上所有（X）

6. 关于 OpenRank，以下说法正确的是：
A. 是 OpenDigger 开源项目中的一个关键指标
B. 是一个开发者协作关系网络上的算法指标
C. 能够量化包括项目、开发者、Issue 单元等不同的社区实体
D.  以上所有（X）

7. 在高校发展开源技术与文化的普及，有利于：
A. 有利于培养学生的代码实践能力
B. 有利于培养学生的沟通交流能力
C. 有利于培养学生的协调领导能力
D.  以上所有（X）

8. 当用 OpenRank 评价一个开发者贡献的时候，以下说法正确的是：
A. 较为客观地反映了一个开发者在开源社区中的影响力与贡献度
B. 能够更具不同的时间区间进行分段评价
C. 当开发者不再社区中活跃时，其 OpenRank 值将逐渐衰减 
D.  以上所有（X）

**Comment by will-ww** [comment]
有几个问题需要考虑：

- 是否要求每个人都需要参与？最好是，有利于推广 OpenRank 的认知度与 oss101 课程
- 是否需要组长提交所有组员答题信息？以方便我们确认进入复赛的队伍，如何提交？
- 是否允许反复刷题？分数线定为多少？例如 80 分？平均80分？
- 进入复赛的同学，是否需要加入群？并进行答疑等相关活动

**Comment by andyhuang18** [comment]
同意学长的看法。针对第二个问题，我的看法是每个同学提交自己的答题结果，并且填写队伍的名称以方便统计进入复赛的队伍名单。

**Comment by tyn1998** [comment]
对的~可能都不需要编程，Excel高手用Excel就能完成需求hh

**Comment by tyn1998** [comment]
金数据竟然不支持问卷内容复制，于是手动copy+paste完成了初赛知识问答问卷：

https://jinshuju.net/f/Y8xE0w

设置了80分为分界线：

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/32434520/229701748-03edb879-5de1-4da1-bf66-5d96bb278864.png">

未通过的样子：

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/32434520/229699652-ab9fe5af-108f-41bf-accb-0c06e740740c.png">

通过的样子：

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/32434520/229702489-f6b9f713-901e-4f6e-8329-10a5f825aed6.png">
