### ISSUE TITLE
[Feature] XSOSI 大屏支持查看历史期数的数据

### ISSUE THREAD

**Issue by xiaoya-yaya** [X-lab2017/open-wonderland#268]
提一个需求～

### 背景
XSOSI 从 2022 年 6 月正式上线，截止 2023 年 4 月一共运行 10 期。这个过程中，参与的组织数、项目数、开发者数、整体 Openrank、每个项目的 OpenRank，每个开发者在具体项目上的贡献占比等都在发生演化，而 [XSOSI 大屏](http://dataease.nzcer.cn/link/E1OQKVBz) 可以很好的展示在每一期中详细的上述数据。

### 目标

[XSOSI 大屏](http://dataease.nzcer.cn/link/E1OQKVBz) 自 2023 年上线，以月度进行更新，每一期会覆盖掉上一期的详细信息。例如现在点进去看到的是当前期数的数据，而过去的期数被覆盖掉了，没办法更直观的感受到每一期数据上的变化。是否有可能在大屏上增加一个选择器，使用户可以动态选择查看具体某一期的详细大屏？

**Comment by zhicheng-ning** [comment]
这一块儿理论上是可以做的，可能还需要 @frank-zsy 提供一些额外的数据字段，例如「期数」，「总津贴」

**Comment by zhicheng-ning** [comment]
Hi @frank-zsy ，学长可以在下个月提供的 xsosi 文件中添加 `period` 和 `award` 两个字段表示某个月份的数据属于 xsosi 第几期和津贴吗

![image](https://user-images.githubusercontent.com/39022409/234245175-f038307a-3070-416b-ac00-a0d0c79b4045.png)

**Comment by frank-zsy** [comment]
@zhicheng-ning 这个可以的

**Comment by tyn1998** [comment]
@zhicheng-ning 我有一个小建议：

<img width="1699" alt="image" src="https://user-images.githubusercontent.com/32434520/236992834-aa39defa-47bd-4477-a63b-05a5e238b3a1.png">

日期选择的样式可以改成暗色的，和整体更协调~
