### ISSUE TITLE
[OpenSODA] 复赛交付材料的金数据问卷制作

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-wonderland#280]
之前有过如何提交材料的讨论，请见：https://github.com/X-lab2017/open-wonderland/issues/262#issuecomment-1491580893

建议根据[6个赛题解读](https://xlab2017.yuque.com/staff-kbz9wp/olpzth/hxlwkpfhyvf2p5xm)中关于“复赛材料交付”的内容，设计一个能够涵盖所有需求的金数据问卷。所有参赛队伍的队长通过该问卷提交复赛材料。

问卷制作后，通过金数据发邮件的形式通知各队伍。

**Comment by will-ww** [comment]
同意！

**Comment by zzzz-niu** [comment]
好～

**Comment by tyn1998** [comment]
已完成。

- 问卷设计：https://jinshuju.net/f/rdOHqM
- 邮件通知：https://github.com/X-lab2017/open-wonderland/issues/264#issuecomment-1605267577
