### ISSUE TITLE
X-lab 实验室网站重构

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#295]

**Comment by will-ww** [comment]
随着时间的发展，X-lab 开放实验室在开源领域的成果与影响力越来越多，有必要对 X-lab 的[官方网站](http://www.x-lab.info/)进行重构与更新，并同 GitHub 进行深度绑定。（上一次更新还是 @leofang327 同学在 2020 年前后整理的）

我们邀请 @wj23027、@andyhuang18、@zhaosj975 一起来先设计并构建，随后由 @zhaosj975 同学来进行后期维护。

几个大的方向与需求如下：
- 充分利用 GitHub 的 Pages 服务进行搭建，该官网本身也是一个开源项目；
- 国际影响力优先，英文优先，然后中英文双语；


🌐几个参考资源如下：
- https://github.com/collections/github-pages-examples
- https://zzetao.github.io/awesome-github-profile/
- https://github.com/ericdaat/research-lab-website
- https://github.com/mmistakes/minimal-mistakes
- https://github.com/iot-kntu/iot-kntu.github.io
- https://github.com/greenelab/lab-website-template
- https://github.com/mpa139/allanlab

大家可以继续补充好的模板与范例~

**Comment by andyhuang18** [comment]
收到，我会花时间阅读参考资源部分。针对先前的<a href='https://github.com/X-lab2017/xlab-website'>网站</a>进行重构。

**Comment by wj23027** [comment]
好的，我们首先需要选择合适的模板，设计一下网站的结构~

**Comment by zhaosj975** [comment]
收到~

**Comment by bifenglin** [comment]
> 好的，我们首先需要选择合适的模板，设计一下网站的结构~

依据我以往经验，可以使用drupal活着wordpress。拥有成熟的内容管理模块和门户网站建设模版

**Comment by will-ww** [comment]
已在 Roadmap 中进行规划，故此关闭~
