### ISSUE TITLE
学院院庆 - 海报展示征集 - 开源生态数据分析与挖掘

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#310]
根据[学院院庆 - 海报展示征集](https://github.com/ECNU/OpenDL/issues/37)，X-lab 实验室开源方向也出一个，把咱们这两年的成果总结下，完成后在实验室门口也挂一个。 

请 @xgdyp @PureNatural 两位同学组织大家来策划，可以这两天讨论框架，周末整理发出来，周一定稿提交（9 月 18 日 10:00 前）~

现场可以演示包括：Hypercrx、大屏、osgraph~

**Comment by xgdyp** [comment]
经过简单的讨论的讨论，确定了海报的框架
<img width="354" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/37795442/a3a94536-8c25-4e52-94d7-6ac127e149b3">

简单的任务安排：
od: @Zzzzzhuzhiwei @xgdyp 

crx: @lhbvvvvv 
osgraph: @wj23027 
leaderboard+大屏: @andyhuang18 
paper&report: @PureNatural 
合稿: @PureNatural 

之前很多项目都写了挺多文档，正好借这个机会把这些文档整理下。

各位老师同学有没有其他想法呢

**Comment by will-ww** [comment]
我的想法建议如下，即围绕突出实验室的**影响力**开展这个展板的设计：

- 名称：OpenDigger: 全球开源数字生态数据挖掘与信息服务系统
- 各个影响力项目 + 好听的名字 + 二维码 + 合作企业 loog 等
- 标准、科研成果等方面

<img width="354" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/15010826/b0bdc333-38c1-480a-8959-0190a643e3f5">

**Comment by PureNatural** [comment]
大家最好今晚之前发我一版～我尽早整合

**Comment by andyhuang18** [comment]
> 大家最好今晚之前发我一版～我尽早整合

好滴，刚考完教资，马上搞～

**Comment by will-ww** [comment]
继续建议：

1、标题

- **开挖（OpenDigger）**：引领全球开源数字生态的智能分析与数据洞察

2、OpenLeaderboard 板块

-  **一得之见**，开启全球开源新视界

4、Hypercrx 板块标题

- **开源之旅**：漫步自由创新的数字生态

5、ossgraph（没变）

- **以图为本**：探索开源社区的无限价值

**Comment by PureNatural** [comment]
![OpenDigger海报V1 2](https://github.com/X-lab2017/open-wonderland/assets/29674550/8d46a5fb-a023-4581-944f-554ca5958dd3)
根据王老师的建议
做了一定的修改，同时基于上个版本，重点突出了opendigger和hypercrx两个实验室的特色项目。
[OpenDigger海报V1.2.pptx](https://github.com/X-lab2017/open-wonderland/files/12641956/OpenDigger.V1.2.pptx)

**Comment by will-ww** [comment]
又改了：

**开挖（OpenDigger）**：引领全球开源数字生态的智能分析与数据洞察

一个故事线：

1. 一得之见：开启开源的新新视界
2. 开源之旅：漫步自由的创新空间
3. 寓享于乐：贡献开源的乐趣满溢
4. 以图为本：探索社区的无限价值

**Comment by PureNatural** [comment]
![幻灯片1](https://github.com/X-lab2017/open-wonderland/assets/29674550/ac10b3a7-0565-4ead-816f-9a40b6db13c0)
[OpenDigger海报V1.3-hfy.pptx](https://github.com/X-lab2017/open-wonderland/files/12642342/OpenDigger.V1.3-hfy.pptx)
大家再看看有没有需要调整的地方。

**Comment by PureNatural** [comment]
![image](https://github.com/X-lab2017/open-wonderland/assets/29674550/66724c05-6b1d-4148-910d-a8b80db7e969)
根据同学们提的建议，将最后论文列表替换成图片，展示更加直观。
[OpenDigger海报V1.4.pptx](https://github.com/X-lab2017/open-wonderland/files/12642470/OpenDigger.V1.4.pptx)

**Comment by will-ww** [comment]
<img width="354" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/15010826/1a8d39d6-9fe5-4be5-9348-ead5945b98df">

**Comment by bifenglin** [comment]
加上opendigger和github地址。
