### ISSUE TITLE
关于在 2023 木兰开源大会上组织 OpenDigger 黑客松活动的建议

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#338]
[2023 木兰开源大会](https://mp.weixin.qq.com/s/5_kUOEIfq8EXt144_Mok7Q)将在[开放原子开发者大会](https://mp.weixin.qq.com/s/cAZJA6Yd-bLSbwBsFMEvbg)期间同步召开，邀请 OpenDigger 社区作为第十三届中国开源黑客松活动的主办方参加，将 OpenDigger 项目作为黑客松活动的赛题来源。

![image](https://github.com/X-lab2017/open-wonderland/assets/15010826/40f8916d-ca11-4c49-b31a-f4f4acffef69)

考虑到 OpenSODA 大赛近期的顺利收官，以及明年 OpenDigger 项目的 Roadmap 计划制定与 OpenRank 的推广需求，可以考虑趁热打铁，进一步通过众创的方式发展 OpenDigger 的影响力。有如下几个可以结合的内容，大家可以一起来参谋下：

**1、基于 OpenDigger 的创新选题项目**

这个方向作为本次黑客松活动最主要目的，可以考虑邀请相关团队一起来参加，完善并进一步巩固已有的生态项目，包括：
- [OpenLeaderboard](https://open-leaderboard.x-lab.info/) 的改版与增强（@andyhuang18）
- [x] #341
- OSGraph 的创新功能与场景（@tyn1998 @蚂蚁）
- Hypercrx 创新功能与场景（@HalloMelon）
- OpenGalaxy 创新功能与场景（@longyanz）
- OpenDashboard 创新功能与场景（@zhicheng-ning）
- PolarDB 开源社区可观测大屏创新（@阿里 PolarDB 团队）
- 开源社区智能问答（@兰韵诗 @Zzzzzhuzhiwei @TieWay59 ）
- OpenSODA 一等奖作品的创新与集成（@[SOLE 回收站](https://atomgit.com/solebins/2023-opensoda-final-t2) @X-lab）
- OpenSODA 二等奖作品的创新与集成（@[ahpu_new_peasants](https://atomgit.com/opendigger-pycli/opendigger-pycli) @孔超 ）
- OpenSODA 二等奖作品的创新与集成（@[数据挖掘先锋队](https://atomgit.com/datamining/2023-opensoda-final-w2)）
- OpenSODA 三等奖/贡献奖作品的创新与集成（@HUBU @游兰）

**2、OpenDigger 2024 年度规划**

这个方向作为本次黑客松活动次要目的，正好利用集中两天的时间，大家一起头脑风暴，为 2024 年度的关键任务做准备，以及可能的合作与业务拓展，包括：

- OpenShare 平台：2024 年度最重要的落地平台，所有事情均围绕它展开（🔥🔥🔥）
- OpenSODA 2024 年的赛题，在今年 [OpenSODA ](https://github.com/ECNU/OpenSODA)大赛成功举办的基础上，优化明年的大赛以及赛题的规划
- OpenDigger + [OSS Insight](https://ossinsight.io/) 的合作方向，例如，通过 [OpenTEA](https://github.com/X-lab2017/OpenTEA101) 走进数据专业课程（面向高校老师，特别是数据专业）
- OpenDigger + 天工开物基金会的合作：高校开源创新教育联盟（@庄表伟）
- OpenDigger + 上海安势的合作（@薛植元）
- OpenDigger + OSPP 的合作（@李梦）
- [x] OpenDigger + [1Panel](https://github.com/1Panel-dev/1Panel) 的合作（@徐桂林 @飞鸽）https://github.com/X-lab2017/open-wonderland/issues/339

**3、OpenDigger 2024 年度学术发展规划**

基于 OpenDigger 开展学术活动，也是后续扩大 OpenDigger 用户数和学术影响力的重要场景，可以考虑：

- OpenPerf 的项目建设与运营，例如在 A 类国际会议上面召开 Workshop，例如 [OpenBench](https://github.com/X-lab2017/OpenBench)
- [x] X-lab2017/open-research#253
- 自然科学基金 2024 年度的申请工作

**Comment by will-ww** [comment]
具体参加人员，可以有几个方面的来源（以 3 个人为一组为例）：

- X-lab 开放实验室：3 组
- Hubu 游老师团队：2 组
- OpenSODA 大赛队伍：2 组
- 阿里、蚂蚁等企业召集：2 组
- 开源社等组织召集：2 组

如果能召集 10 个左右的队伍，就很不错了~

**Comment by TieWay59** [comment]
PS: 庄老师名字写错了。

**Comment by will-ww** [comment]
> PS: 庄老师名字写错了。

Updated~
