### ISSUE TITLE
[2024-01-13] X-lab Day

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#344]
当年，大约 4 年以前：

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/008726b6-b678-493f-8d93-faab69560364" width="500px">
</div>

著名的“[开源点亮未来](https://blog.frankzhao.cn/open_source_lighten_the_future/)”，也是在这一天第一次被提及~
<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/6058b3f5-9a4a-400c-8c27-20176b824641" width="500px">
</div>

  
当时周添一同学 PPT 中的一页：

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/220c9e7d-ce98-4bab-8ef2-93293950f48b" width="500px">
</div>

--------------------
今年，2024 年 1 月 13 日（日程安排）：

**第一阶段：研讨会**
- 时间：1 月 13 日 下午 13 : 30 ~ 17 : 30
- 地点：华东师范大学普陀校区，计算机楼 115 教室
- Agenda：
  - 13 : 00 ~ 13 : 30：**签到**
  - 13 : 30 ~ 13 : 45：**开场**（@will-ww）
  - **第一节：有朋自远方来**（主持人 @HalloMelon ）
  - 13 : 45 ~ 14 : 30：**Graph Data Mining**（@tianyichow, [KTH Royal Institute of Technology](https://www.kth.se/profile/tzho)）
  - 14 : 30 ~ 15 : 00：开源经济学随谈（@zhuangbiaowei 天工开物开源基金会）
  - 15 : 00 ~ 15 : 20：开源社区现状观察（@sunny0826 开放原子开源基金会）
  - 15 : 20 ~ 15 : 30：**茶歇**（拍照）
  - **第二节：一年干了些啥**（主持人 @xgdyp）
  - 15 : 30 ~ 16 : 00：**[图说 X-lab 2023](https://github.com/X-lab2017/open-wonderland/files/13933874/X-lab.2023.pdf)**（@will-ww）
  - 16 : 00 ~ 16 : 15：**OpenRank Leaderboard**（@xiaoya-yaya）
  - 16 : 15 ~ 16 : 30：**OpenPerf**（@bifenglin）
  - 16 : 30 ~ 16 : 45：**OpenDigger**（@PureNatural）
  - 16 : 45 ~ 17 : 00：**OpenSODA**（@tyn1998）
  - 17 : 00 ~ 17 : 15：**2023 中国开源年度报告预览**（@wj23027 @andyhuang18 ）
  - 17 : 15 ~ 17 : 30：**开源点亮未来 2**（@frank-zsy ）
- **注：形式不限，PPT、脱口秀、吐槽大会都行，有趣有料的聊开源~

**第二阶段：晚餐会**
- 时间：1 月 13 日 晚上 18 : 00 ~ 21 : 30
- 地点：**木屋烧烤**（长寿路店）上海市普陀区常德路1221号（长寿路地铁站 6 号口旁）
- **注：不参加第一阶段的老师或同学，可以晚上直接到用餐地点

**第三阶段：自由活动**
- 时间：1 月 13 日 晚上 22 : 00 后
- 事项：KTV、Bar 等

**Comment by will-ww** [comment]
各组织工作建议如下安排：
- 已毕业校友：@bifenglin （华师 & 同济）
- 参加教师：@frank-zsy （田老师等）
- 企业代表：@xiaoya-yaya（老庄等）
- 校内同学：@xgdyp（X-lab、部分水杉）
- 后勤：@HalloMelon（带领一年级四位同学）

**Comment by frank-zsy** [comment]
王老师，13 日的具体日程是如何安排的啊？是下午开始吗？

**Comment by will-ww** [comment]
> 王老师，13 日的具体日程是如何安排的啊？是下午开始吗？

大家可以商量，例如三个阶段：
- 下午 2 点 ~ 5 点：研讨
- 晚餐
- 娱乐活动

**Comment by bifenglin** [comment]
毕业校友参加人员统计如下：


| 姓名   | 人数 | 备注 |
| ------ | ---- | ---- |
| 朱香宁 | 1    |      |
| 李苗进 | 1    |      |
| 陈亮   | 1    |      |
| 史经犇 | 1    |      |
| 翁振杰 | 1    |      |
| 顾业鸣 | 2    |      |
| 范家宽 | 1    |      |
| 周添一 | 1    |      |
| 王皓月 | 2    |      |
| 郭栋   | 1    |      |
| 张礼庆 | 1    |      |
| 林海铭 | 2    |      |
| 徐彦军 | 1    |      |
| 吴松林 | 1    |      |
|        | 17   |      |

**Comment by xiaoya-yaya** [comment]
企业、社区老师参加人员目前如下：
- 庄表伟
- 王永雷
- 郭旭东

**Comment by andyhuang18** [comment]
华师大 参与人员 27 人。

**Comment by zhicheng-ning** [comment]
![09bf83223bced33a43742b502acffb4](https://github.com/X-lab2017/open-wonderland/assets/39022409/ae202943-d387-4635-b762-1e1b007c1225)

**Comment by will-ww** [comment]
已在日程中加入当天的PPT材料（https://github.com/X-lab2017/open-wonderland/files/13933874/X-lab.2023.pdf），大家也可以加一下（也可以是文档链接之类的）~ @PureNatural @tyn1998 @xiaoya-yaya @frank-zsy @wj23027 @bifenglin

**Comment by tianyichow-tcs** [comment]
这里是年会的[slides](https://drive.google.com/file/d/19sTz2l79k2BYOCuwA58qTLCZPNOGpngP/view?usp=sharing)，我做了一些修改，本次分享的第一部分工作刚刚被WWW 2024 接收。第二部分还在投稿评审当中，所以根据评审准则移除了现在不能公开的部分，后续如果大家感兴趣我会更新论文进展。
