### ISSUE TITLE
8、案例分析 @frank-zsy

### ISSUE THREAD

**Issue by frank-zsy** [X-lab2017/open-wonderland#347]
8.1 openEuler 开源社区洞察
8.2 阿里巴巴开源开发者贡献榜
8.3 其他有趣的案例

**Comment by frank-zsy** [comment]
## 8 案例分析

- openEuler 是较好的分析对象，OpenDigger 添加 Gitee 数据后，openEuler 成为国内 OpenRank 最高的社区之一。而且更有趣是 openEuler 社区与 Gitee 深入集成，可在他们的官网中直接对文档发起修改，并自动化转换成 Gitee 的轻量级 PR 提到仓库中，使得贡献者无需跳转到 Gitee 及操作 Git，即可在页面中通过交互式 UI 完成文档的随手优化贡献。
- 阿里巴巴贡献排行榜也是一个很好的案例，既是对 OpenRank 本身的深度采纳，同时产生的科研论文也被 ICSE 收录，可以深入解剖一下。

另外 PolarDB 和 NPM 生态不是很好分析，我想可以引入一下洞察案例，具体思路是：

- 因为我们现在有了大量的开发者地理位置信息，于是有了基于贡献者的国家排行榜。因此我们可以直接洞察出例如中国开发者贡献最多的项目有哪些，肯定有部分不是大厂发起，在目前的圈子中不太容易见到项目，可以拿几个来说说，肯定会比较有趣。这块我深度看看。

**Comment by frank-zsy** [comment]
## openEuler 社区案例分析

在 2023 年，Gitee 数据首次融入 OpenDigger 社区，使得 Gitee 上的项目也参与到了 OpenRank 的计算中。在这一年，openEuler 社区以 16728 的 OpenRank 值超越 PaddlePaddle，成为仅次于 openHarmony 的中国第二大开源社区。

在 2023 年，openEuler 社区吸引了 3941 名开发者参与 Issue 或 PR 的协作讨论，其中有 1934 名贡献者成功为 openEuler 社区的仓库贡献并合入了至少一个 PR。尤其值得一提的是，openEuler 社区在 2023 年初发起了文档捉虫活动，并在社区文档官网中嵌入了与 Gitee 打通的交互式页面贡献机制。这一机制使得开发者在阅读文档时发现错误时，能够在官网上直接修改并一键发起 Gitee 轻量级 PR，无需跳转到 Gitee 平台或进行 Git 操作。这一创新的机制带来的数据变化令人瞩目，openeuler/docs 仓库在 2023 年合入了 7764 个 PR，其中 74% 的 PR 是通过官网页面直接提交的。这一机制的上线也显著提升了每月平均活跃贡献者数量（从 30 人提升到 80 人）和每月平均合入 PR 数量（从 116 个提升到 722 个）。

另一个值得关注的项目是 openeuler/mugen，作为 openEuler 社区的测试框架项目，该项目活跃度极高。在2023 年，有 138 位开发者参与到项目讨论和贡献中，其中 95 位开发者成功合入了PR。该项目在整个 openEuler 社区中的 OpenRank 排名第三，仅次于 openeuler/docs 文档仓库和 openeuler/kernel 内核仓库。优秀的测试框架为开发者提供了快速编写和运行测试用例的便利，可以帮助他们验证贡献代码的正确性和有效性，极大降低了后续贡献的流程成本。

综上所述，openEuler 社区之所以取得较高的 OpenRank 值，并非偶然。他们不仅为高频低门槛的文档贡献设计了几乎零流程成本的交互式贡献机制，还提供了优秀的测试框架，助力贡献者在贡献代码的同时快速验证其正确性。这些优秀的开发者体验优化是各个开源社区值得学习和推广的范例。

**Comment by frank-zsy** [comment]
## 阿里巴巴开源开发者贡献榜

2023 年初，阿里巴巴在其开源官网上推出了[阿里巴巴开源开发者贡献榜](https://opensource.alibaba.com/collection/contribution_leaderboard)。这一榜单的引入标志着对开源社区贡献的全新认可方式，借助 X-lab 实验室提出的 OpenRank 算法，对开发者的贡献进行统计核算，并以排行榜的形式进行公示。

这一榜单的创新之处在于其采用的 OpenRank 算法，该算法深度借鉴了 Apache Way 的理念，并不简单关注开发者贡献量的统计指标，而是将开发者和他们的贡献构建成协作网络并协同评价。这种创新的评价机制使得开发者更能理解到开源社区是一个共同体而不仅仅是技术项目，有助于激励开发者长期深度参与到开源社区的贡献之中。

为了深入理解这一算法和榜单机制对开源社区产生的影响，X-lab 实验室的两位博士生，赵生宇和夏小雅加入阿里巴巴开源办公室并展开了详尽的研究工作。他们不仅从数据统计的角度出发，分析了榜单上线前后社区项目统计指标上的变化情况，还进行了一系列深度访谈，听取了开发者们的真实声音。这一研究的成果不仅为开源社区的发展提供了宝贵的经验和启示，还被收录在软件工程领域的国际顶级学术会议 ICSE 2024 中，引起了学术界的高度关注。

总体而言，阿里巴巴开源贡献者排行榜的推出标志着开源社区评价机制的创新，为广大开发者提供了更方便、全面的贡献认可途径。这一举措不仅激发了开发者的积极性，也推动了开源社区的繁荣发展，为社区注入了新的活力，更是阿里巴巴集团鼓励创新包容创新的重要体现。

---

不过这个似乎数据部分的内容不多，是否可以考虑放入大事记？

**Comment by frank-zsy** [comment]
## 其他中国开发者贡献的顶级仓库列表

使用目前已采集的近千万开发者账号的详细信息，其中包含了中国开发者账号近 20 万，通过分析这 20 万开发者在 2023 年 OpenRank 贡献度情况，获得中国开发者贡献仓库总榜如下：

![image](https://github.com/X-lab2017/open-wonderland/assets/8512426/3e547e58-ba4b-4d95-b22a-90982ed66875)
![image](https://github.com/X-lab2017/open-wonderland/assets/8512426/5b450a8e-a37f-4fdc-b0eb-404ca529db70)

大部分项目是在 OpenRank 大榜中有体现的，比较有趣的项目包括：

- NixOS/nixpkgs：这也是一个国际顶级项目，一个新操作系统的包管理工具，虽然大部分更新都是包信息的更新，但也意味着这个操作系统生态本身的繁荣。
- intel-analytics/BigDL：将 LLM 运行在 Intel XPU 上的运行库，这个仓库 17 年就建立了，到 21 年底时近乎已经废弃，但随着 22 年 LLM 崛起，这个仓库起死回生，目前保持每月 50 人左右的活跃规模。记得王老师 @will-ww 这边有些合作，可以让他们提供一些数据？例如参与共建的企业数量等。
![image](https://github.com/X-lab2017/open-wonderland/assets/8512426/b0f33ffd-5862-469c-91af-958fdca3d514)
- siyuan-note/siyuan：思源笔记，一款隐私优先的国产开源知识管理工具，支持双向知识块级引用，保持每月百人的社区活跃规模。支持订阅商业化，价格非常亲民。
- baidu/amis：百度开源的低代码页面生成框架，低代码项目近年来非常火爆，例如阿里开源的 LowcodeEngine，鸿蒙生态的 DevEco Studio 等为开发者低代码快速开发应用提供了巨大便利。
- cocos/cocos-engine：国产的游戏引擎佼佼者，随着元宇宙概念的兴起，godot 等游戏引擎成为全球重要的顶级开源项目，而国产的游戏引擎 cocos/cocos-engine 也在国内有着优秀的表现。

**Comment by frank-zsy** [comment]
MaaAssistantArknights/MaaAssistantArknights 这个项目不太正经，但很有意思，是明日方舟这款游戏的一个自动化刷日常任务的脚本助手项目，可以在手机模拟器上进行游戏日常任务的自动化执行。这个仓库超过 10k star，每月稳定有 300 多人活跃，非常惊人的活跃度。

**Comment by wj23027** [comment]
hello @frank-zsy ,案例分析的部分似乎还有一些没有完善的地方，近期可以在 [hackmd](https://hackmd.io/@wj23027/report/%2FFJGAACefR_W-UngjBm4_iA#%E5%85%AB-%E6%A1%88%E4%BE%8B%E5%88%86%E6%9E%90) 中完善一下吗~

> 不过这个似乎数据部分的内容不多，是否可以考虑放入大事记？

这个部分和庄老师沟通过啦，决定添加到开源大事记的榜单部分~

> 获得中国开发者贡献仓库总榜如下

这个榜单目前是截图，是否可以调整为引用第二小节的榜单~


> 记得王老师 @will-ww 这边有些合作，可以让他们提供一些数据？例如参与共建的企业数量等。

这部分的内容还有补充吗~

**Comment by frank-zsy** [comment]
这个榜单是在第二部分没有的，样式上我可以让烨男再做一个一样的，看放在第二部分然后在这边引用，还是直接放在这里

**Comment by tyn1998** [comment]
@frank-zsy @wj23027 制作并缩放了两种版本供挑选~

<img width="981" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/32434520/2b0bd193-7153-4048-8a7f-df0ad05f3555">

<img width="781" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/32434520/2c5d54e7-c1c4-42e1-b462-431961b52284">

**Comment by will-ww** [comment]
《[2023 中国开源年度报告](https://kaiyuanshe.github.io/2023-China-Open-Source-Report/)》的已正式发布~🎉
