### ISSUE TITLE
6、开源项目洞察 负责人@PureNatural，@Zzzzzhuzhiwei

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#348]
[开源项目](https://github.com/PureNatural/open-digger/blob/2023_technical_report/notebook/China_open_source_techinical_report_2023.ipynb)洞察方面（注意跳到第 6  部分查看），同样可以逐一来分析一下：

**6.1 不同项目类型数量比例**

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/c07d016c-efcf-4673-94b8-e7e8b5b60ef1" width="500px">
</div>

- **组件框架类型**（Libraries and Frameworks）占比最高（31.36%），充分反映了开源协同创新特点（站在巨人的肩膀上），也是最受开发者喜爱、乐于贡献的类型。
- **应用软件类型**（Application Software）由于其实用性，占比仅次于组件框架类（24.34%），能够使得所有用户（不仅仅局限于开发者）在各个行业与领域使用开源软件。
- **内容资源类型**（Non Software）也有不小的占比（23.17%），这体现了开源这一协同开发模式从软件延伸到全内容领域的趋势，包括文档、教育、艺术、硬件或其他非编程相关领域的创作和贡献。
- **软件工具类型**（Software Tools）的占比为 18.9%，对于开发者这个专业群体来说，是个不容忽视的比例，能够使开发者专注于构建实际的应用程序和软件产品。
- **系统软件类型**（System Software）占比最少（仅 2.3%），体现了基础软件的性质，数量虽少，但价值巨大，难度也是最高的。

**6.2 不同项目类型 OpenRank 加总比例** 

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/6c86a91c-07f4-4dad-87c1-06cfb150a2d1" width="400px">
</div>

进一步，再从 OpenRank 影响力视角看这几个类别：
- 最大的变化，就是**内容资源类型**（Non Software）项目虽然有较高的活跃度，但其影响力相对较低；
- 而**系统软件类型**（System Software）虽然活跃度占比很少，但其影响力占比相对更多，**软件工具类型**（Software Tools）项目也有类似的现象；
-   **组件框架类型**和**应用软件类型**则没有太多变化，都是属于占比较多的类型。

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/0650447d-e0bf-4ae9-8dd6-c545c4cc7dfb" width="700px">
</div>

再从上面的五年 OpenRank 演化图上可以看得出来，**系统软件类型**（System Software）的影响力也是逐年升高、而**内容资源类型**（Non Software）项目的影响力比例是在相对下降这样一个现象。

**6.3 数据库领域项目分析** @birdflyi

这部分除了希望用数据库这个典型领域做各种下钻分析，还想把当年的开源象限（OpenQuadrant）图用起来。

**6.4 AIGC 领域项目分析**

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/88d54ddb-6d21-496a-b0d7-86754eadb727" width="600px">
</div>

- **langchain** 影响力和活跃度双排名第一，备受开发者的关注；
- **transformers** 作为该领域前几年一直的王者，只到 2023 年才被超越，充分展示了其 AIGC 领域奠基性的地位，该项目在学术领域与开源领域影响力均表现不俗；
- stable-diffusion-webui 也是备受开发者关注的 AIGC 工具，尤其在活跃度这块超越 transformers 稳居第二，2024 年影响力超越 transformers 也是大概率事件。
- 部分AIGC 项目在 2023 年开源后影响力与活跃度就迅速增长并位于 Top10 榜单，展示了 AIGC 领域这种极端快速的变化特点。

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/bf6a6d2f-52df-4340-9ab5-8c32a49f8f88" width="600px">
</div>

- 根据类别（模型类、工具类、应用类）划分的分类分析，在活跃度和影响力上总体趋势一致；
- 工具类 AIGC 开源项目的影响力和活跃度均高于模型类和应用类；
- 工具类项目影响力自 2021 年开始增长迅速，在 2023 年超过模型类，整体呈现上升趋势，代表着 2023 年是 AIGC 创新应用开发的大爆发之年，预计后续还会继续走高，从而也同时带动应用类项目的大发展。

**6.5 项目 Topic 分析**

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/03174c9b-d5a3-4723-99da-a669404bfbb7" width="500px">
</div>

目前的 Topic 分析还太简单，需要丰富下~

**Comment by PureNatural** [comment]
6.1 6.2 6.3已补充
其中6.2的猜想基本正确，因为系统软件数量上占比没有优势，但是OpenRank加总占比是高于数量占比的

6.1 能否增加一个五年的演变图， 因为我们是获取了10000个项目后，当时是人工对这一万个项目打得标签，所以说项目类型数量是静态的，如果是按时间维度统计每年每个类型项目的数量的话，相当于每年都需要人工打一次标签，考虑以后可以使用机器学习的方法快速完成标签工作。

我这里加了一个openrank近5年的变化趋势图，能看出来系统软件的影响力逐年增高。

**Comment by Zzzzzhuzhiwei** [comment]
出现次数前十的topic
![image](https://github.com/X-lab2017/open-wonderland/assets/115639837/667eced2-2610-4dff-bca5-38f35c9bf9bf)

出现次数前十的topic下仓库的OpenRank变化(2019-2023)
![image](https://github.com/X-lab2017/open-wonderland/assets/115639837/4ca37e99-0819-4d7e-b5e7-cece6e527e79)

出现次数前十的topic下仓库的2023年OpenRank
![image](https://github.com/X-lab2017/open-wonderland/assets/115639837/560ddeec-b342-49d1-b389-4350c969dbe6)

Hacktoberfest是一个每年十月举办的活动，旨在促进开源社区的发展。它由DigitalOcean与GitHub合作发起，其目标是鼓励更多人参与开源项目，为开源社区做出贡献。它的OpenRank高反映了人们对于开源项目、社区参与和贡献的热情。开发者们积极参与这个活动，通过向开源项目提交Pull Request的方式贡献，从而帮助提升了这个仓库的声誉和影响力。

JavaScript和Python：这两项技术在过去几年中保持了相对稳定的趋势，没有出现大幅度的增长或下降。

**Comment by will-ww** [comment]
《[2023 中国开源年度报告](https://kaiyuanshe.github.io/2023-China-Open-Source-Report/)》的已正式发布~🎉
