### ISSUE TITLE
7、开发者洞察 负责人@bifenglin，@lhbvvvvv

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#349]
根据目前的[报告内容](https://xlab2017.yuque.com/me1x4f/opensource/boe8a1mrvfro9nbn)，可以做些分析与评价：

**7、开发者洞察**

开发者是开源生态与社区的核心组成，可以将开发者分为探索者、参与者、开发者和维护者四个角色：
- **探索者**：star 项目的用户，代表对该项目有一定的兴趣
- **参与者**：在 GitHub 仓储中有过 Issue 或者 Comment 行为的用户
- **开发者**：项目中有 Pull Request 事件的用户
- **维护者**： 参与 PR Reveiw 的用户

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/12c1f3e8-f21d-4b2e-93ea-99e17a8d23ba" width="400px">
</div>

**7.1 开发者类型分析**

TODO

**7.2 开发者工作时间分布**

**1、GitHub 全域开发者工作时间分布**

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/ebc29af6-23b5-42ec-b86c-f3e06fb918b6" width="500px">
</div>

统计 GitHub 全域开发者工作时间，可以看出 GitHub 开发者工作时长分布在 6 时到 21 时更普遍，12 点更为集中，可能是受到定时任务的影响，周六、周日相对更不活跃。

**2、Gitee 全域开发者工作时间分布**

TODO

**3、除去机器人的全域开发者时间分布**

TODO

**7.3 中国开源项目 OpenRank Top 10 开发者时间分布**

- openHarmony
- openEuler
- PaddlePaddle
- MindSpore
- Ant Design
- TiDB
- Apache Doris
- openGauss
- Anolis
- StarRocks

**7.4 开发者的地区分布**

**1、全球开发者经纬度分布**

通过采样 23 万个 GitHub 活跃用户的**经纬度数据**，可视化 GitHub 用户的地理位置分布。

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/80438d07-fcac-411a-b4ed-17a1f9c433bd" width="500px">
</div>

在人口数量众多、且互联网发展较快的地区，例如中国沿海地区、欧洲地区、美国、印度、巴西东南沿海地区有着最为密集的 GitHub 用户分布，在其他居住人口少或者互联网较不发达的地区则相对稀疏。

**2、全球开发者地区分布**

对 130 万个标注了国家信息的 GitHub 活跃用户的**国家/地区数据**进行分析。

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/d1689813-ec87-4cb0-81c7-2047113e62a8" width="500px">
</div>

可以发现美国的人数最多为 23.7 万，中国、印度和巴西则紧随其后，其他拥有一定人口数量和经济水平的国家例如加拿大、澳大利亚以及一些欧洲国家也拥有着较多的用户。

**3、中国开发者地区分布**

对 12.6 万个标注了**中国一级地理行政区**的活跃用户数据进行分析。

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/7fd35223-615c-47f2-8ac7-71d939c91959" width="400px">
</div>

可以发现北京拥有着国内最多的用户，其次是上海、广州和浙江。中国的大部分活跃用户都在东部沿海地区，中部的一些省份例如陕西、湖南、湖北也有拥有不少的活跃用户，值得注意的是四川是除了沿海地区以外拥有最多活跃用户的省份。

**7.5 机器人洞察**

机器人（bot）自动化是开源协作平台中的重要贡献力量，本部分分析了 2023 年全年近 6 亿条仓库事件，涉及 770 万开源仓库，以及 1200 多个机器人账号。

**1、机器人活跃数据分析**

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/2ff68494-54ff-44fc-abeb-494d813cc3d7" width="600px">
</div>

分析 2015 年至 2023 年的机器人活动数据，部分观察如下：
  - 机器人事件数量从 4,217,635 个增长至 304,257,084个，增长趋势显著
  - 从 2019 年起，机器人事件数量急剧上升，尤其是在GitHub平台
  - 2019 年至 2021 年间，GitHub 上机器人账号活动量呈现爆炸式增长
  - 增长是由于 GitHub 自动化、持续集成/持续部署（CI/CD）工具的普及和完善有关
  - 尽管机器人账号数量不多，但每个机器人服务于多个仓库，展现出高效率和广泛影响力

**2、机器人事件类型分析**

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/4c2c087f-697c-4591-ab1e-d473a4ddb75b" width="600px">
</div>

这幅图明显不可用，首先需要解释机器人类型背景，然后用简单直观的可视化表达。

**3、机器人工作时间分布**

类似开发者工作时间分布，可以对机器人的工作时间数据进行分析。

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/f6d59281-50ab-41f4-b071-e59ebda839f7" width="500px">
</div>

可以得到如下洞察：
- 机器人账号的工作时间分布主要集中在凌晨 0 点至 1 点和中午 12 点至 13 点
- 根据全域开发者时区可以推测大多数自动化流程在凌晨和中午时段较为活跃
- 机器人工作活跃时间与工作日和非工作日相关度较小，大多数自动化协作任务为定时任务，较少的自动化任务与对贡献者的活动事件产生响应有关

**Comment by bifenglin** [comment]
机器人事件类型分析修改如下：其中图中的数字表示与2022年的事件数量的差值，纵轴表示与2020年事件数量的百分比差值。


2、机器人事件类型分析
![image](https://github.com/X-lab2017/open-wonderland/assets/15813364/e075d690-5252-4db1-869d-ab44201e381e)

这幅图表展示了2022年与2023年间GitHub各事件类型的数量变化及其增长率。通过对比这两年的数据，我们可以洞察机器人账号在开发流程中的使用趋势：
1. PushEvent（代码推送）:
  a. 当代码被推送到仓库时触发。
  b. 事件数量在2023年相比2022年增长了40.5%，这表明开发者在使用机器人账号进行代码提交方面越发倾向。这种显著增长可能反映了机器人在自动化提交和代码维护方面的广泛应用。
2. ReleaseEvent（发布事件）:
  a. 涉及软件版本的发布。
  b. 增长了28.75%，有明显的增长，暗示着自动化发布工具的使用频率在不断上升。这可能是开发活动全面加强和项目规模扩大的迹象。
3. IssuesEvent（问题评论事件）:
  a. 涉及新问题的创建或问题的状态变更。
  b. 增长了28.02%，表明自动化问题管理活动增加。
4. IssueCommentEvent（问题评论）:
  a. 在问题讨论中添加评论时触发
  b. 2023年相比2022年减少了27.1%，这可能意味着机器人在处理问题方面变得更高效，或者机器人账号的使用策略发生了变化。
5. PullRequestEvent（拉取请求）:
  a. 当拉取请求被审查时触发。
  b. 事件数量减少了52.6%，可能反映了合作模式或代码合并策略的重大变化，以及机器人在代码审查和合并流程中的角色调整。
6. PullRequestReviewEvent（拉取请求审查事件）:
  a. 当拉取请求被审查时触发。
  b. 减少了16.06%，可能是由于PullRequestEvent事件的减少，导致了PullRequestReviewEvent的减少。
7. PullRequestReviewCommentEvent（拉取请求审查评论事件）：
  a. 在拉取请求的代码审查中添加评论时触发。
  b. 增长了20.39%，表明机器人账号在自动化代码审查过程中的互动增加。
8. CreateEvent（创建事件）和DeleteEvent（删除事件）：
  a. 涉及新仓库、分支或标签的创建和删除。
  b. 数量的减少可能指向自动化流程的集中化和标准化，暗示着项目启动和资源分配策略的变化和项目的稳定化或清理流程的优化。
9. CommitCommentEvent（提交评论事件）：
  a. 当用户对代码提交添加评论时触发。
  b. 增长了23.53%。这表明机器人在代码审查和讨论方面的参与增加，可能是由于自动化审查工具的集成和使用增多。
10. GollumEvent（Wiki页面事件）、MemberEvent（团队成员添加事件）、PublicEvent（私有仓库公开事件）、WatchEvent（关注事件）、ForkEvent（复制项目事件）:
  a. GollumEvent涉及Wiki页面的创建或编辑，MemberEvent在新团队成员被添加到项目时触发。PublicEvent事件在私有仓库转为公开时触发。WatchEvent在用户关注（Star）仓库时触发。ForkEvent事件在用户复制（Fork）他人的仓库时触发。
  b. 这些事件的数量非常低，表明机器人账号主要用于特定的自动化任务，如代码推送和自动回复，而在项目管理或社交互动方面的参与相对较少。

**Comment by frank-zsy** [comment]
<img width="1008" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/8512426/124dc5d9-149a-4e5c-8ff2-a79b29391579">

补一张 OpenRank 加权过的 2023 中国开发者经纬度分布图

**Comment by wj23027** [comment]
本周年报会议上有老师指出，绘制地图会存在地图审阅的问题，请问一下本小节地图的图源是什么呢~ @frank-zsy @lhbvvvvv

**Comment by lhbvvvvv** [comment]
> 本周年报会议上有老师指出，绘制地图会存在地图审阅的问题，请问一下本小节地图的图源是什么呢~ @frank-zsy @lhbvvvvv
> 
> 另外， 请问@frank-zsy 学长这张加权图是最终版本吗，可能需要麻烦 @bifenglin 把这张图加进开发者洞察的部分~
> 
> > <img alt="" width="500px" src="https://private-user-images.githubusercontent.com/8512426/295775301-124dc5d9-149a-4e5c-8ff2-a79b29391579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3MTU1MDgsIm5iZiI6MTcwNTcxNTIwOCwicGF0aCI6Ii84NTEyNDI2LzI5NTc3NTMwMS0xMjRkYzVkOS0xNDlhLTRlNWMtOGZmMi1hNzliMjkzOTE1NzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjBUMDE0NjQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU2NjI5ODBmODY1NmEzYmQ0NDQ2NjQ1YWFjYTUzNTkwYjE4ZWI1ODI0ZmEzY2Q0NDg0MGVjMzlkMGJhNTA5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BsU6wNrN_7FuYVvPxSn9jKuevSkGFkw5gaQN1WlfOq4">
> > 补一张 OpenRank 加权过的 2023 中国开发者经纬度分布图

地图是用echarts画的

**Comment by tyn1998** [comment]
@lhbvvvvv 鸿斌，要看下敏感地区的数据源是否正确~ 下面是一个例子：

![image](https://github.com/X-lab2017/open-wonderland/assets/32434520/e80da888-8686-4e06-947f-0f8d200ea2e2)

**Comment by lhbvvvvv** [comment]
两张热力图是用dataease画的所以不存在敏感地区的问题，数据是我自己处理完后放上去的。世界经纬度的散点分布图只用到了经纬度数据没有用到其他，中国地区的经纬度分布是frank用openrank加权后显示的，不出意外地理方面的信息也只用到经纬度，我看到几个地区都是有散点分布的。

地理散点图的模版是用的echarts，地图显示应该是没问题的。之前的热力图南海地区没截全，更改后的是完整的。

**Comment by will-ww** [comment]
《[2023 中国开源年度报告](https://kaiyuanshe.github.io/2023-China-Open-Source-Report/)》的已正式发布~🎉
