### ISSUE TITLE
一个数字课本的典范：《Hello 算法》

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#351]
《Hello 算法》发布了 [1.0.0](https://github.com/krahets/hello-algo/releases/tag/1.0.0) 正式版本，是一个非常优秀的数字课本的典范~

[开源仓库](https://github.com/krahets/hello-algo/releases/tag/1.0.0) +[ 数字课本网站](https://www.hello-algo.com/)的形式，非常简洁优雅~

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/38ede720-fb0d-48e3-8c17-94ba5160c287" width="650px">
</div>

也许咱们的开源和数字素养课程，做一些设计，也能达到类似的效果：
- 《[开源软件通识](https://github.com/X-lab2017/oss101)》
- 《[编程思维与实践](https://github.com/neolee/wop)》
- 《[数据思维与实践](https://github.com/ECNU/Data-Thinking-and-Practice)》

**Comment by andyhuang18** [comment]
很不错的网站，很有参考价值！
