### ISSUE TITLE
关于开发者人数统计的口径问题

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#356]
目前，在开发者人数统计这块，有两个相对一致，但有些不同的数据：
- [1、宏观洞察](https://github.com/X-lab2017/open-wonderland/issues/342) 里面，直接拿的 ClickHouse 里的用户数据，应该是 Github 上所有用户的数据
- [7、开发者洞察](https://github.com/X-lab2017/open-wonderland/issues/349) 里面，是 23 年有日志数据的活跃用户数

![bc650b2768824efb052b59f4a8e5232](https://github.com/X-lab2017/open-wonderland/assets/15010826/c7e4f23c-dd56-4d8d-a8e1-05a2f28340de)

大家觉得怎么来进行说明比较合适？是否也可以把两个数据合并在一起来说，例如：
- 截止 2023 年底，GitHub 美国开发者数 40.90 万，其中 2023 年活跃开发者数量为 23.70 万

**Comment by will-ww** [comment]
另外，在看一下 GitHub 和 Gitee 的官方数据，貌似在数量级上，还是有些出入~

**1、GitHub**（[Octoverse 2023](https://github.blog/2023-11-08-the-state-of-open-source-and-ai/)）

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/bb75f14c-71ab-4bd5-b3a1-521cb08ac6a3" width="600px">
</div>

- 2023 年初，GitHub 全球开发者突破 1 亿
- 美国拥有 2020 万开发者，过去一年开发者增长 21%
- 欧盟 1550 万、印度 1320 万、中国 1060 万（大陆 900 万 + 中国香港 160 万）

**2、Gitee**（《[2023 中国开源开发者报告](https://juejin.cn/post/7317277887567609897)》）

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/7889e205-c603-4a6f-9bb1-b90073563f38" width="500px">
</div>

- 截止 2023 年底，总用户数 1200 万
- 新增用户 200 万

**Comment by will-ww** [comment]
几个疑问点包括：

1、GitHub / Gitee 的官方数据，都是千万级的，是注册用户，而我们统计的都是活跃用户？那么，以美国为例，40.90 万和 23.70 万的区别是什么？
2、根据美国开发者 2023 年的增长率（21%），大约增长了 420 万左右，那么这么看活跃用户占比是非常低的？

**Comment by frank-zsy** [comment]
> 大家觉得怎么来进行说明比较合适？是否也可以把两个数据合并在一起来说，例如：
> 截止 2023 年底，GitHub 美国开发者数 40.90 万，其中 2023 年活跃开发者数量为 23.70 万

这样说可以的，但这里数据量级上和其他报告会有很大出入，需要一定说明：
- 这个数据的基数是基于我们采集的 GitHub 上 1000 万个活跃开发者的数据
- 且是这些开发者中填写了自己的位置信息并且可以被正确解析的，这个量级大概在 200 万左右
- 在这 200 万开发者中，国家为美国的大约为 40 万左右，其中 2023 年活跃的是 24 万左右

> 几个疑问点包括：
> 
> 1、GitHub / Gitee 的官方数据，都是千万级的，是注册用户，而我们统计的都是活跃用户？那么，以美国为例，40.90 万和 23.70 万的区别是什么？ 

如上所述，因为 GitHub 是自己的平台，他们的不同国家开发者数量是通过访问 GitHub 的 IP 地址统计的，但这个数据第三方是没有的，所以我们只能通过采集到的、用户自己填写的数据来进行统计，所以本质上只是一个采样数据，不同国家的开发者比例洞察是有意义的，但绝对值上意义不大。

> 2、根据美国开发者 2023 年的增长率（21%），大约增长了 420 万左右，那么这么看活跃用户占比是非常低的？

同上，如果是 GitHub 的数据，是从访问 IP 来的，有大量的用户是不填写自己的位置数据或不是有效的地理位置数据。

**Comment by will-ww** [comment]
懂了，这样咱们的数据也基本对上了，价值还是很大的。

- GitHub 官方统计大约 1 亿开发者；本次年报中口径是 1000 万活跃开发者中填了地理位置数据的（占总体的 1/20），这样年报中数据放大 20 倍，大约能够对应上全域数值；
- 例如，年报中计算出的 GitHub 美国开发者数 40.90 万（其中 2023 年活跃开发者数量为 23.70 万）；而 GitHub 官方统计的是 2020 万，这个就对上了（40*10*5 = 2000）；
- 因此，咱们不仅能够给出和 GitHub 官方一致的数据，还能给出额外的特色数据，例如，美国开发者数量达到了 2020 万（GitHub 官方数据），其中 2023 年美国活跃开发者数量为 1171（年报能够给出的数据，2200*23.7/40.9）。

再进一步，中国的数据如下：
- 170931/113893，放大 20 倍，即 341 万 GitHub 开发者，其中 2023 年活跃数量为 228 万，活跃率为 66.6%（美国为 57.9%）；
- 印度的数据，177669/107066，即 355 万 GitHub 开发者，其中 2023 年活跃数量为 214 万，活跃率为 60.3%

**Comment by will-ww** [comment]
这样，咱们第一部分宏观洞察，表结构可以这么来建造了：
- 第 1 列：排名
- 第 2 列：国家
- 第 3 列：总体数量（即 408983）
- 第 4 列：总体占比（即用 40.90 / 200）
- 第 5 列：活跃数量（即 236899）
- 第 6 列：活跃率（活跃占比 / 总体占比）

根据第 3 列进行排序。绝对数值，咱们就不在表中体现了，分析中可以说一下和 GitHub 官方数据的一致性即可~

**Comment by will-ww** [comment]
有了全球分布的铺垫，中国地区的统计，就相对简单点了：
- 第 1 列：排名
- 第 2 列：省市
- 第 3 列：总体数量（即北京 32982）
- 第 4 列：全国占比（即北京 32982 / 170931 = 19.3%）
- 第 4 列：估计总量（即北京 32982 * 50 = 16.5 万）

**Comment by frank-zsy** [comment]
有道理，按照比例的话统计上确实是有意义的，由于数据还在持续采集，我给一个更详细的最近数据，看一下具体的差距：

- 目前拉取的头部开发者总量是 915.3W，其中可以有效识别出地理位置的是 196.8W
- 按照 GitHub 全域注册用户数 1 亿计算，采样比例约为 1.968%。
- 其中美国用户总量是 413471，则总体 GitHub 美国用户总量约为 2101W，对应 GitHub 的数据量是 2020W，偏差 4% 左右。
- 中国大陆加港澳台的总开发者数量是 174898，则总体 GitHub 用户量应为 888W，对应 GitHub 的数据量是 1187W，这个偏差较大，可能的结论是中国开发者更不喜欢填写和暴露自己的信息。

不过后续国内各省和直辖市的比例按照总量估计应该是没有问题的，虽然有部分开发者可能没有填写具体到省级或市级，但填写的部分通过比例估计是合理的。

**Comment by wj23027** [comment]
> * 第 5 列：总量（即北京 = 1188 万 * 19.3%= 229 万）
> 
> 这里话有个点，就是 GitHub 上面的中国开发者总体人数的问题，根据 GitHub 2023 年 [Q3 季度的数据](https://github.com/github/innovationgraph/blob/main/data/developers.csv)：
> 
> * CN：9131545
> * HK：1697072
> * TW：1049487
> 
> 总量大概是：11878104 = 1188 万

这里有个问题，香港，澳门，台湾地区是直接用 GitHub 官方的数据，还是与其他省份一样，用“中国开发者总量×比例”估算呢

**Comment by will-ww** [comment]
> > * 第 5 列：总量（即北京 = 1188 万 * 19.3%= 229 万）
> > 
> > 这里话有个点，就是 GitHub 上面的中国开发者总体人数的问题，根据 GitHub 2023 年 [Q3 季度的数据](https://github.com/github/innovationgraph/blob/main/data/developers.csv)：
> > 
> > * CN：9131545
> > * HK：1697072
> > * TW：1049487
> > 
> > 总量大概是：11878104 = 1188 万
> 
> 这里有个问题，香港，澳门，台湾地区是直接用 GitHub 官方的数据，还是与其他省份一样，用“中国开发者总量×比例”估算呢

用“中国开发者总量×比例”估算即可，一是 GitHub 官方的数据只到 Q3，二是我们也可以看看偏差情况~

**Comment by wj23027** [comment]
[开发者人数表格](https://hackmd.io/@wj23027/report/%2FFJGAACefR_W-UngjBm4_iA#132-%E6%B4%BB%E8%B7%83%E7%94%A8%E6%88%B7%E5%9C%B0%E7%90%86%E5%88%86%E5%B8%83%E4%B8%8E%E6%8E%92%E5%90%8D)已经更新完毕~
