### ISSUE TITLE
HyperCRX项目研发例会: 2024-04-10

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-wonderland#395]
### HyperCRX项目教学第三期
- 🕣Time: 14:30~16:30, 2024/04/10
- 📞Tencent Meeting：453-146-448（[link](https://meeting.tencent.com/dm/m0VeQRQkkK26)）
#### 4个任务，4个二人小组（研二+研一）

1. 读ECharts文档可以实现（**难度：1**）： @wangyantong2000 @HalloMelon 
https://github.com/hypertrons/hypertrons-crx/issues/762
2. 依样画葫芦可以完成的feature（**难度：1**）：@Tenth-crew @Zzzzzhuzhiwei 
https://github.com/hypertrons/hypertrons-crx/issues/769
3. 用antd重构Options Page（**难度：2**）： @andyhuang18 @wj23027 
https://github.com/hypertrons/hypertrons-crx/issues/725
4. 涉及到利用GitHub原生元素和样式来完成UI界面（**难度：3**）： @lhbvvvvv 
https://github.com/hypertrons/hypertrons-crx/issues/726

**Comment by tyn1998** [comment]
> 下面评论内容是colorful-calendar教程打卡示范，请提供如下三项内容。

1. origin上的colorful-calendar分支链接：https://github.com/tyn1998/hypertrons-crx/tree/feat/colorful-calendar
2. IDE中的`yarn run start`运行截图
<img width="1512" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/32434520/44857622-98da-458c-8387-4e29a36e8acb">

3. 浏览器中的colorful-calendar特性效果截图
<img width="1393" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/32434520/bf7fc749-0015-4d1c-ad87-c6bb4d94b129">

**Comment by HalloMelon** [comment]
**HyperCRX项目教学第三期**
- 🕣Time: 14:30~16:30, 2024/04/10
- 📞Tencent Meeting：453-146-448（[link](https://meeting.tencent.com/dm/m0VeQRQkkK26)）

**Comment by Tenth-crew** [comment]
1. feat/colourful-calendar分支：https://github.com/Tenth-crew/hypertrons-crx/tree/feat/colourful-calendar
2. 运行截图
![021cd9dacea853943a8063af15d88150](https://github.com/X-lab2017/open-wonderland/assets/68376741/f173fa80-a017-4a25-9450-cf70d5e33715)
3. 特性效果截图
![image](https://github.com/X-lab2017/open-wonderland/assets/68376741/138805a5-0944-4230-84ec-3f7997e926e7)

**Comment by lhbvvvvv** [comment]
1. origin上的colorful-calendar分支链接：https://github.com/lhbvvvvv/hypertrons-crx/tree/feat/colorful-calendar
2. IDE中的`yarn run start`运行截图
![1712718476286](https://github.com/X-lab2017/open-wonderland/assets/104072573/dc0f5dc7-1abc-4068-bcfb-1c524636e235)
3. 浏览器中的colorful-calendar特性效果截图
![1712718865078](https://github.com/X-lab2017/open-wonderland/assets/104072573/2431c965-b8a4-4102-bc3b-5b2ea956df89)

**Comment by andyhuang18** [comment]
1. origin上的colorful-calendar分支链接：https://github.com/andyhuang18/hypertrons-crx/tree/feat/colorful-calendar
2. IDE中的 `yarn run start` 运行截图

<img width="1920" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/50283262/0c809244-dc80-4fa9-bc54-95463c2a1e2f">

3. 浏览器中的colorful-calendar特性效果截图

<img width="1314" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/50283262/0a02d2b2-8edd-43ee-a00f-d052d0d600b2">

**Comment by wangyantong2000** [comment]
origin上的colorful-calendar分支链接：https://github.com/wangyantong2000/hypertrons-crx/tree/feat/colorful-calendar
IDE中的 yarn run start 运行截图
<img width="1504" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/135088663/61056701-48ac-4160-87f1-4c9fddd0762a">

浏览器中的colorful-calendar特性效果截图
<img width="1497" alt="image" src="https://github.com/X-lab2017/open-wonderland/assets/135088663/d60f8734-9e11-46b2-83b6-e39b1849205d">

**Comment by HalloMelon** [comment]
1. origin上的colorful-calendar分支链接：https://github.com/HalloMelon/hypertrons-crx/tree/colorful-calendar
2. IDE中的yarn run start运行截图
![image](https://github.com/X-lab2017/open-wonderland/assets/79428895/6200893f-d163-48a0-a64d-6358f271f36e)

3. 浏览器里显示效果截图
![image](https://github.com/X-lab2017/open-wonderland/assets/79428895/d7e541f2-f629-4618-adda-fc9be335b802)

**Comment by Zzzzzhuzhiwei** [comment]
1.origin上的colorful-calendar分支链接 https://github.com/Zzzzzhuzhiwei/hypertrons-crx/tree/feat/colorful-calendar
2.IDE中的 yarn run start 运行截图
![image](https://github.com/X-lab2017/open-wonderland/assets/115639837/ab2b60df-8e73-4c9d-bce6-a66c4e2a5011)

3.浏览器里显示效果截图
![image](https://github.com/X-lab2017/open-wonderland/assets/115639837/862c30b5-f9b0-4c22-843e-e6d5ce3a13a4)

**Comment by wj23027** [comment]
分支链接：https://github.com/wj23027/hypertrons-crx/tree/feat/colorful-calendar
运行截图：

![image](https://github.com/X-lab2017/open-wonderland/assets/62098023/962fe58c-ec8f-432e-921a-aadf6ee4bf6b)

效果截图：

![image](https://github.com/X-lab2017/open-wonderland/assets/62098023/97bd3d9e-e5f9-424c-8479-14f299f61d15)

**Comment by 41-FortyOne** [comment]
1.分支链接：https://github.com/41-FortyOne/hypertrons-crx/tree/feat/colorful-calendar
2.运行截图：
![image](https://github.com/X-lab2017/open-wonderland/assets/75050154/740a208c-0061-4fb8-b03a-9aec379a95d6)
3.效果截图：
![image](https://github.com/X-lab2017/open-wonderland/assets/75050154/6bac7667-1fdb-469c-b83f-93fecc2c7068)

**Comment by zhaoweijun76** [comment]
1.分支链接：https://github.com/zhaoweijun76/hypertrons-crx/tree/feat/colorful-calendar
2.运行截图：
<img width="1280" alt="1" src="https://github.com/X-lab2017/open-wonderland/assets/165458222/7eadf2dc-7142-415a-b4b8-4b268e1e026f">
<img width="1234" alt="2" src="https://github.com/X-lab2017/open-wonderland/assets/165458222/b5240bdd-1e69-4047-872a-378274f5708e">

**Comment by zhaoweijun76** [comment]
1.分支链接：https://github.com/zhaoweijun76/hypertrons-crx/tree/feat/colorful-calendar
2.运行截图：
<img width="1280" alt="1" src="https://github.com/X-lab2017/open-wonderland/assets/165458222/a5590e19-1aa8-4101-b2b5-d2457a96c07d">
<img width="1234" alt="2" src="https://github.com/X-lab2017/open-wonderland/assets/165458222/18ee7769-336d-4c9a-ac94-b4d22e19c0a1">
