### ISSUE TITLE
OpenRank 在隐私计算方向的拓展与结合（该部分和 CCF-蚂蚁科研基金图计算专项进行结合）

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#416]
该项任务以“[CCF-蚂蚁科研基金图计算专项](https://www.ccf.org.cn/Collaboration/Enterprise_Fund/News/my/2024-06-12/823715.shtml)”申请进行驱动，开始探索图上隐私计算的内容，属于非常前沿的技术，能够为 OpenRank 后续在企业落地应用提供关键的技术支撑，欢迎大家多参与。

相关安排如下：
- 时间：2024 年 7 月 31 日，申请提交
- 方向：基于隐私保护多方图学习的异常检测或社群挖掘
- 题目（初定）：基于隐私保护多方图学习的异常检测、社群挖掘与影响力评估关键技术研究
- 背景与思路：[Ant-Proposal-Idea.pdf](https://github.com/user-attachments/files/16158992/Ant-Proposal-Idea.pdf)
- 申请书模版：[Proposal.docx](https://github.com/user-attachments/files/16159017/Proposal.docx)
- 报告撰写成员：@will-ww @huangfan0 @PureNatural @Peng99999 @zhingoll
- 咨询顾问：@frank-zsy @xiaoya-yaya
- 联合申请人：Wei WANG, [Cen CHEN](https://sites.google.com/site/chencenpersonalwebsite/)

<div align=center>
<img src="https://github.com/X-lab2017/open-wonderland/assets/15010826/54fbfde6-944f-4895-aebb-12f6f1d4eb33" width="500px">
</div>
</BR>

**Comment by will-ww** [comment]
几篇相关论文可以一起参考下，大家可以补充：
- [A federated graph neural network framework for privacy-preserving personalization](https://www.nature.com/articles/s41467-022-30714-9)
- [Privacy-Preserving Graph Machine Learning from Data to Computation: A Survey](https://dl.acm.org/doi/abs/10.1145/3606274.3606280)
- [Decentralized Graph Neural Network for Privacy-Preserving Recommendation](https://arxiv.org/pdf/2308.08072)
- [A Survey of Trustworthy Graph Learning](https://arxiv.org/pdf/2205.10014)
- [Vertically Federated Graph Neural Network for Privacy-Preserving Node Classification](https://www.ijcai.org/proceedings/2022/0272.pdf)
- [Federated Heterogeneous Graph Neural Network for Privacy-preserving Recommendation](http://www.shichuan.org/doc/173.pdf)

**Comment by will-ww** [comment]
### 申请书目录

**1. 项目介绍**
1.1. 基金题目：

1.2. 背景及研究意义 
- 【说明项目当前研究背景、研究意义、主要解决的问题，附上参考文献】
- TODO

1.3. 研究目标
- 【根据基金项目的要求，提炼出研究目标】
- TODO

1.4. 研究方法
- 【说明研究项目拟采用的技术路线与研究方法，突出其创新性和可落地性等优势】
- TODO

2. 研究计划
- 2.1. 项目期限（一般是一年期）
- 2.2. 项目计划（一般分为三或四个阶段）

3. 预期成果（算法原型，论文，专利，技术指标等）
- 按年度列出预期的研究成果，不仅包括产出物的形式（论文、专利、源代码、原型系统等），细化及量化所有合作成果
- 算法原型：完成XXX算法设计，交付一套XXXX系统及其源代码
- 论文：发表蚂蚁认可的CCF-A类或者领域内顶级会议、期刊论文XX篇
- 专利：提交国内、国际专利XX项
- 技术指标：与现有的XXXX baseline相比，提升XXXX指标 XX%
- 业务指标：预计合作成果可落地到蚂蚁的XXX业务（可和蚂蚁研发团队一起讨论）


4. 人力、设备等投入及项目预算
- 4.1. 人力投入
- 4.2. 设备投入
- 4.3. 项目总预算

5. 教授个人简历

**Comment by zhingoll** [comment]
> 几篇相关论文可以一起参考下，大家可以补充：
> 
> * [A federated graph neural network framework for privacy-preserving personalization](https://www.nature.com/articles/s41467-022-30714-9)
> * [Privacy-Preserving Graph Machine Learning from Data to Computation: A Survey](https://dl.acm.org/doi/abs/10.1145/3606274.3606280)
> * [Decentralized Graph Neural Network for Privacy-Preserving Recommendation](https://arxiv.org/pdf/2308.08072)
> * [A Survey of Trustworthy Graph Learning](https://arxiv.org/pdf/2205.10014)
> * [Vertically Federated Graph Neural Network for Privacy-Preserving Node Classification](https://www.ijcai.org/proceedings/2022/0272.pdf)
> * [Federated Heterogeneous Graph Neural Network for Privacy-preserving Recommendation](http://www.shichuan.org/doc/173.pdf)

我来补充两篇中文的吧，
- 这篇是关于图学习隐私保护的中文综述，发表于23年的《计算机学报》
[图学习隐私与安全问题研究综述_先兴平.pdf](https://github.com/user-attachments/files/16242029/_.pdf)
- 这篇是结合负数据库加密和联邦计算的推荐系统，发表于今年的《软件学报》
[基于负数据库的隐私保护图神经网络推荐系统_赵冬冬.pdf](https://github.com/user-attachments/files/16242079/_.pdf)
