### ISSUE TITLE
[文章发布] 🌳构建开源领域的数据生态：OpenDigger 在木兰社区的前行之路

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#54]
木兰社区已经发布：[文章链接](https://mp.weixin.qq.com/s/jeYZ-EujMVKfcxNV5pa24w)

接下来，我们在实验室公众号上也发布一版，**[原文内容](https://xlab2017.yuque.com/msdpvs/me6vqg/rt0pcf)**，稍微再调整下：
- [x] 从实验室的视角 @will-ww 
- [x] 里面的 PPT 全部换成图片和文字 @gymgym1212 
- [x] 其他需要修改和补充的地方 @frank-zsy @xiaoya-Esther 
- [x] 下午4点前更新后，晚上7点请@xgdyp 进行排版发布~

**Comment by xgdyp** [comment]
收到～

**Comment by xgdyp** [comment]
finished

**Comment by will-ww** [comment]
> finished

Great work, many thanks~ @xgdyp

**Comment by will-ww** [comment]
I think next, we can updat the infromation on OpenDigger repo with this summarization article~ @gymgym1212

**Comment by gymgym1212** [comment]
文章中的内容要翻译成英文，全部照搬到 OpenDigger 的 readme 里吗？

我感觉以下几块内容是可以迁移过去的：
1. 语雀中“项目简介”可以补充说明 OpenDigger 的整体结构。
2. 语雀中“应用案例”的部分可以补充 OpenDigger 仓库中 readme 中 Usage 这一节。

其他内容放过去的话，是否有些不合适？

**Comment by will-ww** [comment]
> 文章中的内容要翻译成英文，全部照搬到 OpenDigger 的 readme 里吗？
> 
> 我感觉以下几块内容是可以迁移过去的：
> 
> 1. 语雀中“项目简介”可以补充说明 OpenDigger 的整体结构。
> 2. 语雀中“应用案例”的部分可以补充 OpenDigger 仓库中 readme 中 Usage 这一节。
> 
> 其他内容放过去的话，是否有些不合适？

当然不用，就是能够用得上的一些材料，搬过去就可以了，怎么放、什么形式，都是可以自由决定的了，总之就是宣传与发展OpenDigger~

**Comment by gymgym1212** [comment]
好的，我先调整一下，到时候王老师直接 review 我的 PR ～

**Comment by will-ww** [comment]
> 好的，我先调整一下，到时候王老师直接 review 我的 PR ～

至于谁来做，你可以看看，能否找到社区的人，就最好了~
