### ISSUE TITLE
[文章发布] 🌳 一份开源领域知识的学习清单

### ISSUE THREAD

**Issue by will-ww** [X-lab2017/open-wonderland#58]
GitHub 仓库已经发布：[文章链接](https://github.com/X-lab2017/open-research/blob/main/OpenWriting/%F0%9F%8C%B3%20%E4%B8%80%E4%BB%BD%E5%BC%80%E6%BA%90%E9%A2%86%E5%9F%9F%E7%9F%A5%E8%AF%86%E7%9A%84%E5%AD%A6%E4%B9%A0%E6%B8%85%E5%8D%95.md)

接下来，我们在实验室公众号上也发布一版，[原文内容](https://xlab2017.yuque.com/msdpvs/me6vqg/iua82f)

回头抽空请@xgdyp 抽空发布即可，也不急 ~

**Comment by xgdyp** [comment]
收到，我将下周发布

**Comment by xgdyp** [comment]
finished
https://mp.weixin.qq.com/s?__biz=MzA5MTc0MzEzNQ==&mid=2672497616&idx=1&sn=806d1a3f936a42cb5323b66921ee302b&chksm=8ac80520bdbf8c360eac05b009a226a66fb49932abd91f899934aa708328fc9a8cf35f0f6e1b&token=1512911106&lang=zh_CN#rd
